const hskBand1 = [
  { "chinese": "爱", "traditional": "愛", "pinyin": "ài", "english": "love" },
  { "chinese": "爱好", "traditional": "愛好", "pinyin": "ài hào", "english": "hobby" },
  { "chinese": "八", "traditional": "八", "pinyin": "bā", "english": "eight" },
  { "chinese": "爸爸", "traditional": "爸爸", "pinyin": "bàba", "english": "dad; father" },
  { "chinese": "吧", "traditional": "吧", "pinyin": "ba", "english": "(suggestion particle)" },
  { "chinese": "白", "traditional": "白", "pinyin": "bái", "english": "white" },
  { "chinese": "白天", "traditional": "白天", "pinyin": "bái tiān", "english": "daytime" },
  { "chinese": "百", "traditional": "百", "pinyin": "bǎi", "english": "hundred" },
  { "chinese": "班", "traditional": "班", "pinyin": "bān", "english": "class; shift" },
  { "chinese": "半", "traditional": "半", "pinyin": "bàn", "english": "half" },
  { "chinese": "半年", "traditional": "半年", "pinyin": "bàn nián", "english": "half a year" },
  { "chinese": "半天", "traditional": "半天", "pinyin": "bàn tiān", "english": "half day" },
  { "chinese": "帮", "traditional": "幫", "pinyin": "bāng", "english": "help" },
  { "chinese": "帮忙", "traditional": "幫忙", "pinyin": "bāng máng", "english": "help; lend a hand" },
  { "chinese": "包", "traditional": "包", "pinyin": "bāo", "english": "bag; package" },
  { "chinese": "包子", "traditional": "包子", "pinyin": "bāo zi", "english": "steamed bun" },
  { "chinese": "杯", "traditional": "杯", "pinyin": "bēi", "english": "cup; glass" },
  { "chinese": "杯子", "traditional": "杯子", "pinyin": "bēi zi", "english": "cup; glass" },
  { "chinese": "北", "traditional": "北", "pinyin": "běi", "english": "north" },
  { "chinese": "北边", "traditional": "北邊", "pinyin": "běi biān", "english": "north side" },
  { "chinese": "北京", "traditional": "北京", "pinyin": "běi jīng", "english": "Beijing" },
  { "chinese": "本", "traditional": "本", "pinyin": "běn", "english": "(measure word for books)" },
  { "chinese": "本子", "traditional": "本子", "pinyin": "běn zi", "english": "notebook" },
  { "chinese": "比", "traditional": "比", "pinyin": "bǐ", "english": "than; compared to" },
  { "chinese": "别", "traditional": "別", "pinyin": "bié", "english": "don't" },
  { "chinese": "别的", "traditional": "別的", "pinyin": "bié de", "english": "other; different" },
  { "chinese": "别人", "traditional": "別人", "pinyin": "bié rén", "english": "other people" },
  { "chinese": "病", "traditional": "病", "pinyin": "bìng", "english": "illness; sick" },
  { "chinese": "病人", "traditional": "病人", "pinyin": "bìng rén", "english": "patient" },
  { "chinese": "不大", "traditional": "不大", "pinyin": "bú dà", "english": "not very; not too" },
  { "chinese": "不对", "traditional": "不對", "pinyin": "bú duì", "english": "wrong; incorrect" },
  { "chinese": "不客气", "traditional": "不客氣", "pinyin": "bú kè qì", "english": "you're welcome" },
  { "chinese": "不用", "traditional": "不用", "pinyin": "bú yòng", "english": "no need; don't have to" },
  { "chinese": "不", "traditional": "不", "pinyin": "bù", "english": "no; not" },
  { "chinese": "菜", "traditional": "菜", "pinyin": "cài", "english": "dish; vegetable" },
  { "chinese": "茶", "traditional": "茶", "pinyin": "chá", "english": "tea" },
  { "chinese": "差", "traditional": "差", "pinyin": "chà", "english": "poor; lacking; differ" },
  { "chinese": "常", "traditional": "常", "pinyin": "cháng", "english": "often; frequently" },
  { "chinese": "常常", "traditional": "常常", "pinyin": "cháng cháng", "english": "often; frequently" },
  { "chinese": "唱", "traditional": "唱", "pinyin": "chàng", "english": "sing" },
  { "chinese": "唱歌", "traditional": "唱歌", "pinyin": "chàng gē", "english": "sing a song" },
  { "chinese": "车", "traditional": "車", "pinyin": "chē", "english": "car; vehicle" },
  { "chinese": "车票", "traditional": "車票", "pinyin": "chē piào", "english": "ticket (for transport)" },
  { "chinese": "车上", "traditional": "車上", "pinyin": "chē shàng", "english": "on the vehicle" },
  { "chinese": "车站", "traditional": "車站", "pinyin": "chē zhàn", "english": "station; stop" },
  { "chinese": "吃", "traditional": "吃", "pinyin": "chī", "english": "eat" },
  { "chinese": "吃饭", "traditional": "吃飯", "pinyin": "chī fàn", "english": "eat a meal" },
  { "chinese": "出", "traditional": "出", "pinyin": "chū", "english": "go out; exit" },
  { "chinese": "出来", "traditional": "出來", "pinyin": "chū lái", "english": "come out" },
  { "chinese": "出去", "traditional": "出去", "pinyin": "chū qù", "english": "go out" },
  { "chinese": "穿", "traditional": "穿", "pinyin": "chuān", "english": "wear; put on" },
  { "chinese": "床", "traditional": "床", "pinyin": "chuáng", "english": "bed" },
  { "chinese": "次", "traditional": "次", "pinyin": "cì", "english": "(measure word for times)" },
  { "chinese": "从", "traditional": "從", "pinyin": "cóng", "english": "from" },
  { "chinese": "错", "traditional": "錯", "pinyin": "cuò", "english": "wrong; mistake" },
  { "chinese": "打", "traditional": "打", "pinyin": "dǎ", "english": "hit; play; make" },
  { "chinese": "打车", "traditional": "打車", "pinyin": "dǎ chē", "english": "take a taxi" },
  { "chinese": "打电话", "traditional": "打電話", "pinyin": "dǎ diàn huà", "english": "make a phone call" },
  { "chinese": "打开", "traditional": "打開", "pinyin": "dǎ kāi", "english": "open; turn on" },
  { "chinese": "打球", "traditional": "打球", "pinyin": "dǎ qiú", "english": "play ball" },
  { "chinese": "大", "traditional": "大", "pinyin": "dà", "english": "big; large" },
  { "chinese": "大学", "traditional": "大學", "pinyin": "dà xué", "english": "university" },
  { "chinese": "大学生", "traditional": "大學生", "pinyin": "dà xué shēng", "english": "university student" },
  { "chinese": "到", "traditional": "到", "pinyin": "dào", "english": "arrive; reach; to" },
  { "chinese": "得到", "traditional": "得到", "pinyin": "dé dào", "english": "get; obtain" },
  { "chinese": "地", "traditional": "地", "pinyin": "de", "english": "(adverbial particle)" },
  { "chinese": "的", "traditional": "的", "pinyin": "de", "english": "(possessive particle)" },
  { "chinese": "等", "traditional": "等", "pinyin": "děng", "english": "wait" },
  { "chinese": "地", "traditional": "地", "pinyin": "dì", "english": "ground; place" },
  { "chinese": "地点", "traditional": "地點", "pinyin": "dì diǎn", "english": "location; place" },
  { "chinese": "地方", "traditional": "地方", "pinyin": "dì fang", "english": "place; location" },
  { "chinese": "地上", "traditional": "地上", "pinyin": "dì shàng", "english": "on the ground" },
  { "chinese": "地图", "traditional": "地圖", "pinyin": "dì tú", "english": "map" },
  { "chinese": "弟弟", "traditional": "弟弟", "pinyin": "dì di", "english": "younger brother" },
  { "chinese": "第", "traditional": "第", "pinyin": "dì", "english": "(ordinal prefix)" },
  { "chinese": "点", "traditional": "點", "pinyin": "diǎn", "english": "o'clock; point; a little" },
  { "chinese": "电", "traditional": "電", "pinyin": "diàn", "english": "electricity" },
  { "chinese": "电话", "traditional": "電話", "pinyin": "diàn huà", "english": "telephone" },
  { "chinese": "电脑", "traditional": "電腦", "pinyin": "diàn nǎo", "english": "computer" },
  { "chinese": "电视", "traditional": "電視", "pinyin": "diàn shì", "english": "television" },
  { "chinese": "电视机", "traditional": "電視機", "pinyin": "diàn shì jī", "english": "television set" },
  { "chinese": "电影", "traditional": "電影", "pinyin": "diàn yǐng", "english": "movie; film" },
  { "chinese": "电影院", "traditional": "電影院", "pinyin": "diàn yǐng yuàn", "english": "cinema; movie theater" },
  { "chinese": "东", "traditional": "東", "pinyin": "dōng", "english": "east" },
  { "chinese": "东边", "traditional": "東邊", "pinyin": "dōng biān", "english": "east side" },
  { "chinese": "东西", "traditional": "東西", "pinyin": "dōng xi", "english": "thing; stuff" },
  { "chinese": "动", "traditional": "動", "pinyin": "dòng", "english": "move" },
  { "chinese": "动作", "traditional": "動作", "pinyin": "dòng zuò", "english": "action; movement" },
  { "chinese": "都", "traditional": "都", "pinyin": "dōu", "english": "all; both" },
  { "chinese": "读", "traditional": "讀", "pinyin": "dú", "english": "read" },
  { "chinese": "读书", "traditional": "讀書", "pinyin": "dú shū", "english": "read books; study" },
  { "chinese": "对", "traditional": "對", "pinyin": "duì", "english": "correct; right; toward" },
  { "chinese": "对不起", "traditional": "對不起", "pinyin": "duì bu qǐ", "english": "sorry; excuse me" },
  { "chinese": "多", "traditional": "多", "pinyin": "duō", "english": "many; much; more" },
  { "chinese": "多少", "traditional": "多少", "pinyin": "duō shao", "english": "how many; how much" },
  { "chinese": "饿", "traditional": "餓", "pinyin": "è", "english": "hungry" },
  { "chinese": "儿子", "traditional": "兒子", "pinyin": "ér zi", "english": "son" },
  { "chinese": "二", "traditional": "二", "pinyin": "èr", "english": "two" },
  { "chinese": "饭", "traditional": "飯", "pinyin": "fàn", "english": "rice; meal" },
  { "chinese": "饭店", "traditional": "飯店", "pinyin": "fàn diàn", "english": "restaurant" },
  { "chinese": "房间", "traditional": "房間", "pinyin": "fáng jiān", "english": "room" },
  { "chinese": "房子", "traditional": "房子", "pinyin": "fáng zi", "english": "house" },
  { "chinese": "放", "traditional": "放", "pinyin": "fàng", "english": "put; place" },
  { "chinese": "放假", "traditional": "放假", "pinyin": "fàng jià", "english": "have a vacation" },
  { "chinese": "放学", "traditional": "放學", "pinyin": "fàng xué", "english": "finish school" },
  { "chinese": "飞", "traditional": "飛", "pinyin": "fēi", "english": "fly" },
  { "chinese": "飞机", "traditional": "飛機", "pinyin": "fēi jī", "english": "airplane" },
  { "chinese": "非常", "traditional": "非常", "pinyin": "fēi cháng", "english": "very; extremely" },
  { "chinese": "分", "traditional": "分", "pinyin": "fēn", "english": "minute; divide" },
  { "chinese": "风", "traditional": "風", "pinyin": "fēng", "english": "wind" },
  { "chinese": "干", "traditional": "乾", "pinyin": "gān", "english": "dry" },
  { "chinese": "干净", "traditional": "乾淨", "pinyin": "gān jìng", "english": "clean" },
  { "chinese": "干", "traditional": "幹", "pinyin": "gàn", "english": "do; work" },
  { "chinese": "干什么", "traditional": "幹什麼", "pinyin": "gàn shén me", "english": "do what; what are you doing" },
  { "chinese": "高", "traditional": "高", "pinyin": "gāo", "english": "tall; high" },
  { "chinese": "高兴", "traditional": "高興", "pinyin": "gāo xìng", "english": "happy; glad" },
  { "chinese": "告诉", "traditional": "告訴", "pinyin": "gào su", "english": "tell; inform" },
  { "chinese": "哥哥", "traditional": "哥哥", "pinyin": "gē ge", "english": "older brother" },
  { "chinese": "歌", "traditional": "歌", "pinyin": "gē", "english": "song" },
  { "chinese": "个", "traditional": "個", "pinyin": "gè", "english": "(general measure word)" },
  { "chinese": "给", "traditional": "給", "pinyin": "gěi", "english": "give; for" },
  { "chinese": "跟", "traditional": "跟", "pinyin": "gēn", "english": "with; follow" },
  { "chinese": "工人", "traditional": "工人", "pinyin": "gōng rén", "english": "worker" },
  { "chinese": "工作", "traditional": "工作", "pinyin": "gōng zuò", "english": "work; job" },
  { "chinese": "关", "traditional": "關", "pinyin": "guān", "english": "close; turn off" },
  { "chinese": "关上", "traditional": "關上", "pinyin": "guān shàng", "english": "close; shut" },
  { "chinese": "贵", "traditional": "貴", "pinyin": "guì", "english": "expensive" },
  { "chinese": "国", "traditional": "國", "pinyin": "guó", "english": "country; nation" },
  { "chinese": "国家", "traditional": "國家", "pinyin": "guó jiā", "english": "country; nation" },
  { "chinese": "国外", "traditional": "國外", "pinyin": "guó wài", "english": "abroad; overseas" },
  { "chinese": "过", "traditional": "過", "pinyin": "guò", "english": "pass; cross; (past experience)" },
  { "chinese": "还", "traditional": "還", "pinyin": "hái", "english": "still; also" },
  { "chinese": "还是", "traditional": "還是", "pinyin": "hái shi", "english": "or; still" },
  { "chinese": "还有", "traditional": "還有", "pinyin": "hái yǒu", "english": "also have; in addition" },
  { "chinese": "孩子", "traditional": "孩子", "pinyin": "hái zi", "english": "child; children" },
  { "chinese": "汉语", "traditional": "漢語", "pinyin": "hàn yǔ", "english": "Chinese language" },
  { "chinese": "汉字", "traditional": "漢字", "pinyin": "hàn zì", "english": "Chinese character" },
  { "chinese": "好", "traditional": "好", "pinyin": "hǎo", "english": "good; well" },
  { "chinese": "好吃", "traditional": "好吃", "pinyin": "hǎo chī", "english": "delicious; tasty" },
  { "chinese": "好看", "traditional": "好看", "pinyin": "hǎo kàn", "english": "good-looking; attractive" },
  { "chinese": "好听", "traditional": "好聽", "pinyin": "hǎo tīng", "english": "pleasant to hear" },
  { "chinese": "好玩儿", "traditional": "好玩兒", "pinyin": "hǎo wánr", "english": "fun; interesting" },
  { "chinese": "号", "traditional": "號", "pinyin": "hào", "english": "number; date" },
  { "chinese": "喝", "traditional": "喝", "pinyin": "hē", "english": "drink" },
  { "chinese": "和", "traditional": "和", "pinyin": "hé", "english": "and; with" },
  { "chinese": "很", "traditional": "很", "pinyin": "hěn", "english": "very" },
  { "chinese": "后", "traditional": "後", "pinyin": "hòu", "english": "back; behind; after" },
  { "chinese": "后边", "traditional": "後邊", "pinyin": "hòu biān", "english": "behind; back" },
  { "chinese": "后天", "traditional": "後天", "pinyin": "hòu tiān", "english": "day after tomorrow" },
  { "chinese": "花", "traditional": "花", "pinyin": "huā", "english": "flower" },
  { "chinese": "话", "traditional": "話", "pinyin": "huà", "english": "words; speech" },
  { "chinese": "坏", "traditional": "壞", "pinyin": "huài", "english": "bad; broken" },
  { "chinese": "还", "traditional": "還", "pinyin": "huán", "english": "return; pay back" },
  { "chinese": "回", "traditional": "回", "pinyin": "huí", "english": "return; go back" },
  { "chinese": "回答", "traditional": "回答", "pinyin": "huí dá", "english": "answer; reply" },
  { "chinese": "回到", "traditional": "回到", "pinyin": "huí dào", "english": "return to" },
  { "chinese": "回家", "traditional": "回家", "pinyin": "huí jiā", "english": "go home" },
  { "chinese": "回来", "traditional": "回來", "pinyin": "huí lái", "english": "come back" },
  { "chinese": "回去", "traditional": "回去", "pinyin": "huí qù", "english": "go back" },
  { "chinese": "会", "traditional": "會", "pinyin": "huì", "english": "can; know how to; meeting" },
  { "chinese": "火车", "traditional": "火車", "pinyin": "huǒ chē", "english": "train" },
  { "chinese": "机场", "traditional": "機場", "pinyin": "jī chǎng", "english": "airport" },
  { "chinese": "机票", "traditional": "機票", "pinyin": "jī piào", "english": "plane ticket" },
  { "chinese": "鸡蛋", "traditional": "雞蛋", "pinyin": "jī dàn", "english": "egg" },
  { "chinese": "几", "traditional": "幾", "pinyin": "jǐ", "english": "how many; several; a few" },
  { "chinese": "记", "traditional": "記", "pinyin": "jì", "english": "remember; record" },
  { "chinese": "记得", "traditional": "記得", "pinyin": "jì de", "english": "remember" },
  { "chinese": "记住", "traditional": "記住", "pinyin": "jì zhù", "english": "remember; keep in mind" },
  { "chinese": "家", "traditional": "家", "pinyin": "jiā", "english": "home; family" },
  { "chinese": "家里", "traditional": "家裡", "pinyin": "jiā lǐ", "english": "at home" },
  { "chinese": "家人", "traditional": "家人", "pinyin": "jiā rén", "english": "family members" },
  { "chinese": "间", "traditional": "間", "pinyin": "jiān", "english": "between; (measure word for rooms)" },
  { "chinese": "见", "traditional": "見", "pinyin": "jiàn", "english": "see; meet" },
  { "chinese": "见面", "traditional": "見面", "pinyin": "jiàn miàn", "english": "meet" },
  { "chinese": "教", "traditional": "教", "pinyin": "jiāo", "english": "teach" },
  { "chinese": "叫", "traditional": "叫", "pinyin": "jiào", "english": "call; be called" },
  { "chinese": "教学楼", "traditional": "教學樓", "pinyin": "jiào xué lóu", "english": "teaching building" },
  { "chinese": "姐姐", "traditional": "姐姐", "pinyin": "jiě jie", "english": "older sister" },
  { "chinese": "介绍", "traditional": "介紹", "pinyin": "jiè shào", "english": "introduce" },
  { "chinese": "今年", "traditional": "今年", "pinyin": "jīn nián", "english": "this year" },
  { "chinese": "今天", "traditional": "今天", "pinyin": "jīn tiān", "english": "today" },
  { "chinese": "进", "traditional": "進", "pinyin": "jìn", "english": "enter; go in" },
  { "chinese": "进来", "traditional": "進來", "pinyin": "jìn lái", "english": "come in" },
  { "chinese": "进去", "traditional": "進去", "pinyin": "jìn qù", "english": "go in" },
  { "chinese": "九", "traditional": "九", "pinyin": "jiǔ", "english": "nine" },
  { "chinese": "就", "traditional": "就", "pinyin": "jiù", "english": "then; right away; just" },
  { "chinese": "觉得", "traditional": "覺得", "pinyin": "jué de", "english": "feel; think" },
  { "chinese": "开", "traditional": "開", "pinyin": "kāi", "english": "open; start; drive" },
  { "chinese": "开车", "traditional": "開車", "pinyin": "kāi chē", "english": "drive a car" },
  { "chinese": "开会", "traditional": "開會", "pinyin": "kāi huì", "english": "have a meeting" },
  { "chinese": "开玩笑", "traditional": "開玩笑", "pinyin": "kāi wán xiào", "english": "joke; kid" },
  { "chinese": "看", "traditional": "看", "pinyin": "kàn", "english": "look; see; watch" },
  { "chinese": "看病", "traditional": "看病", "pinyin": "kàn bìng", "english": "see a doctor" },
  { "chinese": "看到", "traditional": "看到", "pinyin": "kàn dào", "english": "see" },
  { "chinese": "看见", "traditional": "看見", "pinyin": "kàn jiàn", "english": "see" },
  { "chinese": "考", "traditional": "考", "pinyin": "kǎo", "english": "test; exam" },
  { "chinese": "考试", "traditional": "考試", "pinyin": "kǎo shì", "english": "exam; test" },
  { "chinese": "渴", "traditional": "渴", "pinyin": "kě", "english": "thirsty" },
  { "chinese": "课", "traditional": "課", "pinyin": "kè", "english": "class; lesson" },
  { "chinese": "课本", "traditional": "課本", "pinyin": "kè běn", "english": "textbook" },
  { "chinese": "课文", "traditional": "課文", "pinyin": "kè wén", "english": "text" },
  { "chinese": "口", "traditional": "口", "pinyin": "kǒu", "english": "mouth; (measure word)" },
  { "chinese": "块", "traditional": "塊", "pinyin": "kuài", "english": "piece; yuan (currency)" },
  { "chinese": "快", "traditional": "快", "pinyin": "kuài", "english": "fast; quick" },
  { "chinese": "来", "traditional": "來", "pinyin": "lái", "english": "come" },
  { "chinese": "来到", "traditional": "來到", "pinyin": "lái dào", "english": "come to; arrive" },
  { "chinese": "老", "traditional": "老", "pinyin": "lǎo", "english": "old; aged" },
  { "chinese": "老人", "traditional": "老人", "pinyin": "lǎo rén", "english": "elderly person" },
  { "chinese": "老师", "traditional": "老師", "pinyin": "lǎo shī", "english": "teacher" },
  { "chinese": "了", "traditional": "了", "pinyin": "le", "english": "(completion particle)" },
  { "chinese": "累", "traditional": "累", "pinyin": "lèi", "english": "tired" },
  { "chinese": "冷", "traditional": "冷", "pinyin": "lěng", "english": "cold" },
  { "chinese": "里", "traditional": "裡", "pinyin": "lǐ", "english": "in; inside" },
  { "chinese": "里边", "traditional": "裡邊", "pinyin": "lǐ biān", "english": "inside" },
  { "chinese": "两", "traditional": "兩", "pinyin": "liǎng", "english": "two" },
  { "chinese": "零", "traditional": "零", "pinyin": "líng", "english": "zero" },
  { "chinese": "六", "traditional": "六", "pinyin": "liù", "english": "six" },
  { "chinese": "楼", "traditional": "樓", "pinyin": "lóu", "english": "floor; building" },
  { "chinese": "楼上", "traditional": "樓上", "pinyin": "lóu shàng", "english": "upstairs" },
  { "chinese": "楼下", "traditional": "樓下", "pinyin": "lóu xià", "english": "downstairs" },
  { "chinese": "路", "traditional": "路", "pinyin": "lù", "english": "road; way" },
  { "chinese": "路口", "traditional": "路口", "pinyin": "lù kǒu", "english": "intersection" },
  { "chinese": "路上", "traditional": "路上", "pinyin": "lù shàng", "english": "on the road" },
  { "chinese": "妈妈", "traditional": "媽媽", "pinyin": "mā ma", "english": "mom; mother" },
  { "chinese": "马路", "traditional": "馬路", "pinyin": "mǎ lù", "english": "road; street" },
  { "chinese": "马上", "traditional": "馬上", "pinyin": "mǎ shàng", "english": "immediately; right away" },
  { "chinese": "吗", "traditional": "嗎", "pinyin": "ma", "english": "(question particle)" },
  { "chinese": "买", "traditional": "買", "pinyin": "mǎi", "english": "buy" },
  { "chinese": "慢", "traditional": "慢", "pinyin": "màn", "english": "slow" },
  { "chinese": "忙", "traditional": "忙", "pinyin": "máng", "english": "busy" },
  { "chinese": "毛", "traditional": "毛", "pinyin": "máo", "english": "10 cents; hair" },
  { "chinese": "没", "traditional": "沒", "pinyin": "méi", "english": "not have; no" },
  { "chinese": "没关系", "traditional": "沒關係", "pinyin": "méi guān xi", "english": "it doesn't matter" },
  { "chinese": "没什么", "traditional": "沒什麼", "pinyin": "méi shén me", "english": "it's nothing" },
  { "chinese": "没事儿", "traditional": "沒事兒", "pinyin": "méi shìr", "english": "it's okay; no problem" },
  { "chinese": "没有", "traditional": "沒有", "pinyin": "méi yǒu", "english": "don't have; there isn't" },
  { "chinese": "妹妹", "traditional": "妹妹", "pinyin": "mèi mei", "english": "younger sister" },
  { "chinese": "门", "traditional": "門", "pinyin": "mén", "english": "door; gate" },
  { "chinese": "门口", "traditional": "門口", "pinyin": "mén kǒu", "english": "doorway; entrance" },
  { "chinese": "门票", "traditional": "門票", "pinyin": "mén piào", "english": "admission ticket" },
  { "chinese": "们", "traditional": "們", "pinyin": "men", "english": "(plural suffix)" },
  { "chinese": "米饭", "traditional": "米飯", "pinyin": "mǐ fàn", "english": "rice" },
  { "chinese": "面包", "traditional": "麵包", "pinyin": "miàn bāo", "english": "bread" },
  { "chinese": "面条儿", "traditional": "麵條兒", "pinyin": "miàn tiáor", "english": "noodles" },
  { "chinese": "名字", "traditional": "名字", "pinyin": "míng zi", "english": "name" },
  { "chinese": "明白", "traditional": "明白", "pinyin": "míng bai", "english": "understand; clear" },
  { "chinese": "明年", "traditional": "明年", "pinyin": "míng nián", "english": "next year" },
  { "chinese": "明天", "traditional": "明天", "pinyin": "míng tiān", "english": "tomorrow" },
  { "chinese": "拿", "traditional": "拿", "pinyin": "ná", "english": "take; hold" },
  { "chinese": "哪", "traditional": "哪", "pinyin": "nǎ", "english": "which" },
  { "chinese": "哪里", "traditional": "哪裡", "pinyin": "nǎ lǐ", "english": "where" },
  { "chinese": "哪儿", "traditional": "哪兒", "pinyin": "nǎr", "english": "where" },
  { "chinese": "哪些", "traditional": "哪些", "pinyin": "nǎ xiē", "english": "which ones" },
  { "chinese": "那", "traditional": "那", "pinyin": "nà", "english": "that" },
  { "chinese": "那边", "traditional": "那邊", "pinyin": "nà biān", "english": "over there" },
  { "chinese": "那里", "traditional": "那裡", "pinyin": "nà lǐ", "english": "there" },
  { "chinese": "那儿", "traditional": "那兒", "pinyin": "nàr", "english": "there" },
  { "chinese": "那些", "traditional": "那些", "pinyin": "nà xiē", "english": "those" },
  { "chinese": "奶", "traditional": "奶", "pinyin": "nǎi", "english": "milk" },
  { "chinese": "奶奶", "traditional": "奶奶", "pinyin": "nǎi nai", "english": "grandmother (paternal)" },
  { "chinese": "男", "traditional": "男", "pinyin": "nán", "english": "male; man" },
  { "chinese": "男孩儿", "traditional": "男孩兒", "pinyin": "nán háir", "english": "boy" },
  { "chinese": "男朋友", "traditional": "男朋友", "pinyin": "nán péng yǒu", "english": "boyfriend" },
  { "chinese": "男人", "traditional": "男人", "pinyin": "nán rén", "english": "man" },
  { "chinese": "男生", "traditional": "男生", "pinyin": "nán shēng", "english": "male student; boy" },
  { "chinese": "南", "traditional": "南", "pinyin": "nán", "english": "south" },
  { "chinese": "南边", "traditional": "南邊", "pinyin": "nán biān", "english": "south side" },
  { "chinese": "难", "traditional": "難", "pinyin": "nán", "english": "difficult; hard" },
  { "chinese": "呢", "traditional": "呢", "pinyin": "ne", "english": "(question particle)" },
  { "chinese": "能", "traditional": "能", "pinyin": "néng", "english": "can; able to" },
  { "chinese": "你", "traditional": "你", "pinyin": "nǐ", "english": "you" },
  { "chinese": "你们", "traditional": "你們", "pinyin": "nǐ men", "english": "you (plural)" },
  { "chinese": "年", "traditional": "年", "pinyin": "nián", "english": "year" },
  { "chinese": "您", "traditional": "您", "pinyin": "nín", "english": "you (polite)" },
  { "chinese": "牛奶", "traditional": "牛奶", "pinyin": "niú nǎi", "english": "milk" },
  { "chinese": "女", "traditional": "女", "pinyin": "nǚ", "english": "female; woman" },
  { "chinese": "女儿", "traditional": "女兒", "pinyin": "nǚ ér", "english": "daughter" },
  { "chinese": "女孩儿", "traditional": "女孩兒", "pinyin": "nǚ háir", "english": "girl" },
  { "chinese": "女朋友", "traditional": "女朋友", "pinyin": "nǚ péng yǒu", "english": "girlfriend" },
  { "chinese": "女人", "traditional": "女人", "pinyin": "nǚ rén", "english": "woman" },
  { "chinese": "女生", "traditional": "女生", "pinyin": "nǚ shēng", "english": "female student; girl" },
  { "chinese": "旁边", "traditional": "旁邊", "pinyin": "páng biān", "english": "beside; next to" },
  { "chinese": "跑", "traditional": "跑", "pinyin": "pǎo", "english": "run" },
  { "chinese": "朋友", "traditional": "朋友", "pinyin": "péng yǒu", "english": "friend" },
  { "chinese": "票", "traditional": "票", "pinyin": "piào", "english": "ticket" },
  { "chinese": "七", "traditional": "七", "pinyin": "qī", "english": "seven" },
  { "chinese": "起", "traditional": "起", "pinyin": "qǐ", "english": "get up; rise" },
  { "chinese": "起床", "traditional": "起床", "pinyin": "qǐ chuáng", "english": "get up" },
  { "chinese": "起来", "traditional": "起來", "pinyin": "qǐ lái", "english": "get up; stand up" },
  { "chinese": "汽车", "traditional": "汽車", "pinyin": "qì chē", "english": "car" },
  { "chinese": "前", "traditional": "前", "pinyin": "qián", "english": "front; before" },
  { "chinese": "前边", "traditional": "前邊", "pinyin": "qián biān", "english": "in front" },
  { "chinese": "前天", "traditional": "前天", "pinyin": "qián tiān", "english": "day before yesterday" },
  { "chinese": "钱", "traditional": "錢", "pinyin": "qián", "english": "money" },
  { "chinese": "钱包", "traditional": "錢包", "pinyin": "qián bāo", "english": "wallet" },
  { "chinese": "请", "traditional": "請", "pinyin": "qǐng", "english": "please; invite" },
  { "chinese": "请假", "traditional": "請假", "pinyin": "qǐng jià", "english": "ask for leave" },
  { "chinese": "请进", "traditional": "請進", "pinyin": "qǐng jìn", "english": "please come in" },
  { "chinese": "请问", "traditional": "請問", "pinyin": "qǐng wèn", "english": "excuse me; may I ask" },
  { "chinese": "请坐", "traditional": "請坐", "pinyin": "qǐng zuò", "english": "please sit down" },
  { "chinese": "球", "traditional": "球", "pinyin": "qiú", "english": "ball" },
  { "chinese": "去", "traditional": "去", "pinyin": "qù", "english": "go" },
  { "chinese": "去年", "traditional": "去年", "pinyin": "qù nián", "english": "last year" },
  { "chinese": "热", "traditional": "熱", "pinyin": "rè", "english": "hot" },
  { "chinese": "人", "traditional": "人", "pinyin": "rén", "english": "person; people" },
  { "chinese": "认识", "traditional": "認識", "pinyin": "rèn shi", "english": "know; recognize" },
  { "chinese": "认真", "traditional": "認真", "pinyin": "rèn zhēn", "english": "serious; earnest" },
  { "chinese": "日", "traditional": "日", "pinyin": "rì", "english": "day; sun" },
  { "chinese": "日期", "traditional": "日期", "pinyin": "rì qī", "english": "date" },
  { "chinese": "肉", "traditional": "肉", "pinyin": "ròu", "english": "meat" },
  { "chinese": "三", "traditional": "三", "pinyin": "sān", "english": "three" },
  { "chinese": "山", "traditional": "山", "pinyin": "shān", "english": "mountain" },
  { "chinese": "商场", "traditional": "商場", "pinyin": "shāng chǎng", "english": "shopping mall" },
  { "chinese": "商店", "traditional": "商店", "pinyin": "shāng diàn", "english": "store; shop" },
  { "chinese": "上", "traditional": "上", "pinyin": "shàng", "english": "up; on; go to" },
  { "chinese": "上班", "traditional": "上班", "pinyin": "shàng bān", "english": "go to work" },
  { "chinese": "上边", "traditional": "上邊", "pinyin": "shàng biān", "english": "above; on top" },
  { "chinese": "上车", "traditional": "上車", "pinyin": "shàng chē", "english": "get on (vehicle)" },
  { "chinese": "上次", "traditional": "上次", "pinyin": "shàng cì", "english": "last time" },
  { "chinese": "上课", "traditional": "上課", "pinyin": "shàng kè", "english": "attend class" },
  { "chinese": "上网", "traditional": "上網", "pinyin": "shàng wǎng", "english": "go online" },
  { "chinese": "上午", "traditional": "上午", "pinyin": "shàng wǔ", "english": "morning" },
  { "chinese": "上学", "traditional": "上學", "pinyin": "shàng xué", "english": "go to school" },
  { "chinese": "少", "traditional": "少", "pinyin": "shǎo", "english": "few; little; less" },
  { "chinese": "谁", "traditional": "誰", "pinyin": "shéi", "english": "who" },
  { "chinese": "身上", "traditional": "身上", "pinyin": "shēn shàng", "english": "on one's body" },
  { "chinese": "身体", "traditional": "身體", "pinyin": "shēn tǐ", "english": "body; health" },
  { "chinese": "什么", "traditional": "什麼", "pinyin": "shén me", "english": "what" },
  { "chinese": "生病", "traditional": "生病", "pinyin": "shēng bìng", "english": "get sick" },
  { "chinese": "生气", "traditional": "生氣", "pinyin": "shēng qì", "english": "get angry" },
  { "chinese": "生日", "traditional": "生日", "pinyin": "shēng rì", "english": "birthday" },
  { "chinese": "十", "traditional": "十", "pinyin": "shí", "english": "ten" },
  { "chinese": "时候", "traditional": "時候", "pinyin": "shí hou", "english": "time; when" },
  { "chinese": "时间", "traditional": "時間", "pinyin": "shí jiān", "english": "time" },
  { "chinese": "事", "traditional": "事", "pinyin": "shì", "english": "matter; thing" },
  { "chinese": "试", "traditional": "試", "pinyin": "shì", "english": "try; test" },
  { "chinese": "是", "traditional": "是", "pinyin": "shì", "english": "be; yes" },
  { "chinese": "是不是", "traditional": "是不是", "pinyin": "shì bú shì", "english": "is it or not" },
  { "chinese": "手", "traditional": "手", "pinyin": "shǒu", "english": "hand" },
  { "chinese": "手机", "traditional": "手機", "pinyin": "shǒu jī", "english": "mobile phone" },
  { "chinese": "书", "traditional": "書", "pinyin": "shū", "english": "book" },
  { "chinese": "书包", "traditional": "書包", "pinyin": "shū bāo", "english": "schoolbag" },
  { "chinese": "书店", "traditional": "書店", "pinyin": "shū diàn", "english": "bookstore" },
  { "chinese": "树", "traditional": "樹", "pinyin": "shù", "english": "tree" },
  { "chinese": "水", "traditional": "水", "pinyin": "shuǐ", "english": "water" },
  { "chinese": "水果", "traditional": "水果", "pinyin": "shuǐ guǒ", "english": "fruit" },
  { "chinese": "睡", "traditional": "睡", "pinyin": "shuì", "english": "sleep" },
  { "chinese": "睡觉", "traditional": "睡覺", "pinyin": "shuì jiào", "english": "sleep; go to bed" },
  { "chinese": "说", "traditional": "說", "pinyin": "shuō", "english": "say; speak" },
  { "chinese": "说话", "traditional": "說話", "pinyin": "shuō huà", "english": "talk; speak" },
  { "chinese": "四", "traditional": "四", "pinyin": "sì", "english": "four" },
  { "chinese": "送", "traditional": "送", "pinyin": "sòng", "english": "give; send" },
  { "chinese": "岁", "traditional": "歲", "pinyin": "suì", "english": "years old" },
  { "chinese": "他", "traditional": "他", "pinyin": "tā", "english": "he; him" },
  { "chinese": "他们", "traditional": "他們", "pinyin": "tā men", "english": "they; them (male)" },
  { "chinese": "她", "traditional": "她", "pinyin": "tā", "english": "she; her" },
  { "chinese": "她们", "traditional": "她們", "pinyin": "tā men", "english": "they; them (female)" },
  { "chinese": "太", "traditional": "太", "pinyin": "tài", "english": "too; very" },
  { "chinese": "天", "traditional": "天", "pinyin": "tiān", "english": "day; sky" },
  { "chinese": "天气", "traditional": "天氣", "pinyin": "tiān qì", "english": "weather" },
  { "chinese": "听", "traditional": "聽", "pinyin": "tīng", "english": "listen; hear" },
  { "chinese": "听到", "traditional": "聽到", "pinyin": "tīng dào", "english": "hear" },
  { "chinese": "听见", "traditional": "聽見", "pinyin": "tīng jiàn", "english": "hear" },
  { "chinese": "听写", "traditional": "聽寫", "pinyin": "tīng xiě", "english": "dictation" },
  { "chinese": "同学", "traditional": "同學", "pinyin": "tóng xué", "english": "classmate" },
  { "chinese": "图书馆", "traditional": "圖書館", "pinyin": "tú shū guǎn", "english": "library" },
  { "chinese": "外", "traditional": "外", "pinyin": "wài", "english": "outside; foreign" },
  { "chinese": "外边", "traditional": "外邊", "pinyin": "wài biān", "english": "outside" },
  { "chinese": "外国", "traditional": "外國", "pinyin": "wài guó", "english": "foreign country" },
  { "chinese": "外语", "traditional": "外語", "pinyin": "wài yǔ", "english": "foreign language" },
  { "chinese": "玩儿", "traditional": "玩兒", "pinyin": "wánr", "english": "play; have fun" },
  { "chinese": "晚", "traditional": "晚", "pinyin": "wǎn", "english": "late; evening" },
  { "chinese": "晚饭", "traditional": "晚飯", "pinyin": "wǎn fàn", "english": "dinner" },
  { "chinese": "晚上", "traditional": "晚上", "pinyin": "wǎn shang", "english": "evening; night" },
  { "chinese": "网上", "traditional": "網上", "pinyin": "wǎng shàng", "english": "online; on the internet" },
  { "chinese": "网友", "traditional": "網友", "pinyin": "wǎng yǒu", "english": "internet friend" },
  { "chinese": "忘", "traditional": "忘", "pinyin": "wàng", "english": "forget" },
  { "chinese": "忘记", "traditional": "忘記", "pinyin": "wàng jì", "english": "forget" },
  { "chinese": "问", "traditional": "問", "pinyin": "wèn", "english": "ask" },
  { "chinese": "我", "traditional": "我", "pinyin": "wǒ", "english": "I; me" },
  { "chinese": "我们", "traditional": "我們", "pinyin": "wǒ men", "english": "we; us" },
  { "chinese": "五", "traditional": "五", "pinyin": "wǔ", "english": "five" },
  { "chinese": "午饭", "traditional": "午飯", "pinyin": "wǔ fàn", "english": "lunch" },
  { "chinese": "西", "traditional": "西", "pinyin": "xī", "english": "west" },
  { "chinese": "西边", "traditional": "西邊", "pinyin": "xī biān", "english": "west side" },
  { "chinese": "洗", "traditional": "洗", "pinyin": "xǐ", "english": "wash" },
  { "chinese": "洗手间", "traditional": "洗手間", "pinyin": "xǐ shǒu jiān", "english": "restroom; bathroom" },
  { "chinese": "喜欢", "traditional": "喜歡", "pinyin": "xǐ huan", "english": "like; enjoy" },
  { "chinese": "下", "traditional": "下", "pinyin": "xià", "english": "down; below; next" },
  { "chinese": "下班", "traditional": "下班", "pinyin": "xià bān", "english": "get off work" },
  { "chinese": "下边", "traditional": "下邊", "pinyin": "xià biān", "english": "below; under" },
  { "chinese": "下车", "traditional": "下車", "pinyin": "xià chē", "english": "get off (vehicle)" },
  { "chinese": "下次", "traditional": "下次", "pinyin": "xià cì", "english": "next time" },
  { "chinese": "下课", "traditional": "下課", "pinyin": "xià kè", "english": "finish class" },
  { "chinese": "下午", "traditional": "下午", "pinyin": "xià wǔ", "english": "afternoon" },
  { "chinese": "下雨", "traditional": "下雨", "pinyin": "xià yǔ", "english": "rain" },
  { "chinese": "先", "traditional": "先", "pinyin": "xiān", "english": "first; before" },
  { "chinese": "先生", "traditional": "先生", "pinyin": "xiān sheng", "english": "mister; sir" },
  { "chinese": "现在", "traditional": "現在", "pinyin": "xiàn zài", "english": "now" },
  { "chinese": "想", "traditional": "想", "pinyin": "xiǎng", "english": "think; want" },
  { "chinese": "小", "traditional": "小", "pinyin": "xiǎo", "english": "small; little" },
  { "chinese": "小孩儿", "traditional": "小孩兒", "pinyin": "xiǎo háir", "english": "child" },
  { "chinese": "小姐", "traditional": "小姐", "pinyin": "xiǎo jiě", "english": "miss; young lady" },
  { "chinese": "小朋友", "traditional": "小朋友", "pinyin": "xiǎo péng yǒu", "english": "child; kid" },
  { "chinese": "小时", "traditional": "小時", "pinyin": "xiǎo shí", "english": "hour" },
  { "chinese": "小学", "traditional": "小學", "pinyin": "xiǎo xué", "english": "elementary school" },
  { "chinese": "小学生", "traditional": "小學生", "pinyin": "xiǎo xué shēng", "english": "elementary student" },
  { "chinese": "笑", "traditional": "笑", "pinyin": "xiào", "english": "laugh; smile" },
  { "chinese": "写", "traditional": "寫", "pinyin": "xiě", "english": "write" },
  { "chinese": "谢谢", "traditional": "謝謝", "pinyin": "xiè xie", "english": "thank you" },
  { "chinese": "新", "traditional": "新", "pinyin": "xīn", "english": "new" },
  { "chinese": "新年", "traditional": "新年", "pinyin": "xīn nián", "english": "new year" },
  { "chinese": "星期", "traditional": "星期", "pinyin": "xīng qī", "english": "week" },
  { "chinese": "星期日", "traditional": "星期日", "pinyin": "xīng qī rì", "english": "Sunday" },
  { "chinese": "星期天", "traditional": "星期天", "pinyin": "xīng qī tiān", "english": "Sunday" },
  { "chinese": "行", "traditional": "行", "pinyin": "xíng", "english": "okay; all right" },
  { "chinese": "休息", "traditional": "休息", "pinyin": "xiū xi", "english": "rest; take a break" },
  { "chinese": "学", "traditional": "學", "pinyin": "xué", "english": "study; learn" },
  { "chinese": "学生", "traditional": "學生", "pinyin": "xué sheng", "english": "student" },
  { "chinese": "学习", "traditional": "學習", "pinyin": "xué xí", "english": "study; learn" },
  { "chinese": "学校", "traditional": "學校", "pinyin": "xué xiào", "english": "school" },
  { "chinese": "学院", "traditional": "學院", "pinyin": "xué yuàn", "english": "college; institute" },
  { "chinese": "要", "traditional": "要", "pinyin": "yào", "english": "want; need; will" },
  { "chinese": "爷爷", "traditional": "爺爺", "pinyin": "yé ye", "english": "grandfather (paternal)" },
  { "chinese": "也", "traditional": "也", "pinyin": "yě", "english": "also; too" },
  { "chinese": "页", "traditional": "頁", "pinyin": "yè", "english": "page" },
  { "chinese": "一", "traditional": "一", "pinyin": "yī", "english": "one" },
  { "chinese": "衣服", "traditional": "衣服", "pinyin": "yī fu", "english": "clothes" },
  { "chinese": "医生", "traditional": "醫生", "pinyin": "yī shēng", "english": "doctor" },
  { "chinese": "医院", "traditional": "醫院", "pinyin": "yī yuàn", "english": "hospital" },
  { "chinese": "一半", "traditional": "一半", "pinyin": "yí bàn", "english": "half" },
  { "chinese": "一会儿", "traditional": "一會兒", "pinyin": "yí huìr", "english": "a little while" },
  { "chinese": "一块儿", "traditional": "一塊兒", "pinyin": "yí kuàir", "english": "together" },
  { "chinese": "一下儿", "traditional": "一下兒", "pinyin": "yí xiàr", "english": "a little bit" },
  { "chinese": "一样", "traditional": "一樣", "pinyin": "yí yàng", "english": "same; alike" },
  { "chinese": "一边", "traditional": "一邊", "pinyin": "yì biān", "english": "one side; while" },
  { "chinese": "一点儿", "traditional": "一點兒", "pinyin": "yī diǎnr", "english": "a little bit" },
  { "chinese": "一起", "traditional": "一起", "pinyin": "yì qǐ", "english": "together" },
  { "chinese": "一些", "traditional": "一些", "pinyin": "yì xiē", "english": "some; a few" },
  { "chinese": "用", "traditional": "用", "pinyin": "yòng", "english": "use" },
  { "chinese": "有", "traditional": "有", "pinyin": "yǒu", "english": "have; there is" },
  { "chinese": "有的", "traditional": "有的", "pinyin": "yǒu de", "english": "some" },
  { "chinese": "有名", "traditional": "有名", "pinyin": "yǒu míng", "english": "famous" },
  { "chinese": "有时候", "traditional": "有時候", "pinyin": "yǒu shí hou", "english": "sometimes" },
  { "chinese": "有些", "traditional": "有些", "pinyin": "yǒu xiē", "english": "some; a few" },
  { "chinese": "有用", "traditional": "有用", "pinyin": "yǒu yòng", "english": "useful" },
  { "chinese": "右", "traditional": "右", "pinyin": "yòu", "english": "right" },
  { "chinese": "右边", "traditional": "右邊", "pinyin": "yòu biān", "english": "right side" },
  { "chinese": "雨", "traditional": "雨", "pinyin": "yǔ", "english": "rain" },
  { "chinese": "元", "traditional": "元", "pinyin": "yuán", "english": "yuan (currency)" },
  { "chinese": "远", "traditional": "遠", "pinyin": "yuǎn", "english": "far" },
  { "chinese": "月", "traditional": "月", "pinyin": "yuè", "english": "month; moon" },
  { "chinese": "再", "traditional": "再", "pinyin": "zài", "english": "again; then" },
  { "chinese": "再见", "traditional": "再見", "pinyin": "zài jiàn", "english": "goodbye" },
  { "chinese": "在", "traditional": "在", "pinyin": "zài", "english": "at; in; on" },
  { "chinese": "在家", "traditional": "在家", "pinyin": "zài jiā", "english": "at home" },
  { "chinese": "早", "traditional": "早", "pinyin": "zǎo", "english": "early; morning" },
  { "chinese": "早饭", "traditional": "早飯", "pinyin": "zǎo fàn", "english": "breakfast" },
  { "chinese": "早上", "traditional": "早上", "pinyin": "zǎo shang", "english": "morning" },
  { "chinese": "怎么", "traditional": "怎麼", "pinyin": "zěn me", "english": "how; why" },
  { "chinese": "站", "traditional": "站", "pinyin": "zhàn", "english": "station; stand" },
  { "chinese": "找", "traditional": "找", "pinyin": "zhǎo", "english": "look for; find" },
  { "chinese": "找到", "traditional": "找到", "pinyin": "zhǎo dào", "english": "find" },
  { "chinese": "这", "traditional": "這", "pinyin": "zhè", "english": "this" },
  { "chinese": "这边", "traditional": "這邊", "pinyin": "zhè biān", "english": "this side; here" },
  { "chinese": "这里", "traditional": "這裡", "pinyin": "zhè lǐ", "english": "here" },
  { "chinese": "这儿", "traditional": "這兒", "pinyin": "zhèr", "english": "here" },
  { "chinese": "这些", "traditional": "這些", "pinyin": "zhè xiē", "english": "these" },
  { "chinese": "着", "traditional": "著", "pinyin": "zhe", "english": "(progressive aspect particle)" },
  { "chinese": "真", "traditional": "真", "pinyin": "zhēn", "english": "really; true" },
  { "chinese": "真的", "traditional": "真的", "pinyin": "zhēn de", "english": "really; truly" },
  { "chinese": "正", "traditional": "正", "pinyin": "zhèng", "english": "just; exactly" },
  { "chinese": "正在", "traditional": "正在", "pinyin": "zhèng zài", "english": "in the process of" },
  { "chinese": "知道", "traditional": "知道", "pinyin": "zhī dào", "english": "know" },
  { "chinese": "知识", "traditional": "知識", "pinyin": "zhī shi", "english": "knowledge" },
  { "chinese": "中", "traditional": "中", "pinyin": "zhōng", "english": "middle; center; China" },
  { "chinese": "中国", "traditional": "中國", "pinyin": "zhōng guó", "english": "China" },
  { "chinese": "中间", "traditional": "中間", "pinyin": "zhōng jiān", "english": "middle; between" },
  { "chinese": "中文", "traditional": "中文", "pinyin": "zhōng wén", "english": "Chinese language" },
  { "chinese": "中午", "traditional": "中午", "pinyin": "zhōng wǔ", "english": "noon" },
  { "chinese": "中学", "traditional": "中學", "pinyin": "zhōng xué", "english": "middle school" },
  { "chinese": "中学生", "traditional": "中學生", "pinyin": "zhōng xué shēng", "english": "middle school student" },
  { "chinese": "重", "traditional": "重", "pinyin": "zhòng", "english": "heavy; important" },
  { "chinese": "重要", "traditional": "重要", "pinyin": "zhòng yào", "english": "important" },
  { "chinese": "住", "traditional": "住", "pinyin": "zhù", "english": "live; reside" },
  { "chinese": "准备", "traditional": "準備", "pinyin": "zhǔn bèi", "english": "prepare; get ready" },
  { "chinese": "桌子", "traditional": "桌子", "pinyin": "zhuō zi", "english": "table; desk" },
  { "chinese": "字", "traditional": "字", "pinyin": "zì", "english": "character; word" },
  { "chinese": "子", "traditional": "子", "pinyin": "zi", "english": "(noun suffix)" },
  { "chinese": "走", "traditional": "走", "pinyin": "zǒu", "english": "walk; go; leave" },
  { "chinese": "走路", "traditional": "走路", "pinyin": "zǒu lù", "english": "walk" },
  { "chinese": "最", "traditional": "最", "pinyin": "zuì", "english": "most" },
  { "chinese": "最好", "traditional": "最好", "pinyin": "zuì hǎo", "english": "best; had better" },
  { "chinese": "最后", "traditional": "最後", "pinyin": "zuì hòu", "english": "last; final" },
  { "chinese": "昨天", "traditional": "昨天", "pinyin": "zuó tiān", "english": "yesterday" },
  { "chinese": "左", "traditional": "左", "pinyin": "zuǒ", "english": "left" },
  { "chinese": "左边", "traditional": "左邊", "pinyin": "zuǒ biān", "english": "left side" },
  { "chinese": "坐", "traditional": "坐", "pinyin": "zuò", "english": "sit" },
  { "chinese": "坐下", "traditional": "坐下", "pinyin": "zuò xià", "english": "sit down" },
  { "chinese": "做", "traditional": "做", "pinyin": "zuò", "english": "do; make" }
];
