const hskBand2 = [
  { "chinese": "啊", "traditional": "啊", "pinyin": "a", "english": "ah; oh (auxiliary word)" },
  { "chinese": "爱情", "traditional": "愛情", "pinyin": "àiqíng", "english": "love; romance" },
  { "chinese": "爱人", "traditional": "愛人", "pinyin": "àirén", "english": "lover; spouse" },
  { "chinese": "安静", "traditional": "安靜", "pinyin": "ānjìng", "english": "quiet; peaceful; calm" },
  { "chinese": "安全", "traditional": "安全", "pinyin": "ānquán", "english": "safe; secure; safety" },
  { "chinese": "白色", "traditional": "白色", "pinyin": "báisè", "english": "white; white color" },
  { "chinese": "班长", "traditional": "班長", "pinyin": "bānzhǎng", "english": "class monitor; squad leader" },
  { "chinese": "办", "traditional": "辦", "pinyin": "bàn", "english": "to do; to handle; to manage" },
  { "chinese": "办法", "traditional": "辦法", "pinyin": "bànfǎ", "english": "way; method; solution" },
  { "chinese": "办公室", "traditional": "辦公室", "pinyin": "bàngōngshì", "english": "office" },
  { "chinese": "半夜", "traditional": "半夜", "pinyin": "bànyè", "english": "midnight; middle of the night" },
  { "chinese": "帮助", "traditional": "幫助", "pinyin": "bāngzhù", "english": "to help; to assist" },
  { "chinese": "饱", "traditional": "飽", "pinyin": "bǎo", "english": "full; satisfied (after eating)" },
  { "chinese": "报名", "traditional": "報名", "pinyin": "bàomíng", "english": "to register; to sign up" },
  { "chinese": "报纸", "traditional": "報紙", "pinyin": "bàozhǐ", "english": "newspaper" },
  { "chinese": "北方", "traditional": "北方", "pinyin": "běifāng", "english": "north; northern region" },
  { "chinese": "背", "traditional": "背", "pinyin": "bēi", "english": "to carry on one's back" },
  { "chinese": "比如", "traditional": "比如", "pinyin": "bǐrú", "english": "for example; such as" },
  { "chinese": "比如说", "traditional": "比如說", "pinyin": "bǐrúshuō", "english": "for instance; for example" },
  { "chinese": "笔", "traditional": "筆", "pinyin": "bǐ", "english": "pen; pencil" },
  { "chinese": "笔记", "traditional": "筆記", "pinyin": "bǐjì", "english": "notes; to take notes" },
  { "chinese": "笔记本", "traditional": "筆記本", "pinyin": "bǐjìběn", "english": "notebook; laptop" },
  { "chinese": "必须", "traditional": "必須", "pinyin": "bìxū", "english": "must; have to; necessary" },
  { "chinese": "边", "traditional": "邊", "pinyin": "biān", "english": "side; edge; border" },
  { "chinese": "变", "traditional": "變", "pinyin": "biàn", "english": "to change; to become" },
  { "chinese": "变成", "traditional": "變成", "pinyin": "biànchéng", "english": "to become; to turn into" },
  { "chinese": "遍", "traditional": "遍", "pinyin": "biàn", "english": "time; round (measure word)" },
  { "chinese": "表", "traditional": "表", "pinyin": "biǎo", "english": "watch; form; table" },
  { "chinese": "表示", "traditional": "表示", "pinyin": "biǎoshì", "english": "to express; to show; to indicate" },
  { "chinese": "不错", "traditional": "不錯", "pinyin": "bùcuò", "english": "not bad; pretty good" },
  { "chinese": "不但", "traditional": "不但", "pinyin": "búdàn", "english": "not only" },
  { "chinese": "不够", "traditional": "不夠", "pinyin": "bùgòu", "english": "not enough; insufficient" },
  { "chinese": "不过", "traditional": "不過", "pinyin": "búguò", "english": "but; however; only" },
  { "chinese": "不太", "traditional": "不太", "pinyin": "bútài", "english": "not very; not too" },
  { "chinese": "不要", "traditional": "不要", "pinyin": "búyào", "english": "don't; must not" },
  { "chinese": "不好意思", "traditional": "不好意思", "pinyin": "bùhǎoyìsi", "english": "sorry; embarrassed" },
  { "chinese": "不久", "traditional": "不久", "pinyin": "bùjiǔ", "english": "soon; before long" },
  { "chinese": "不满", "traditional": "不滿", "pinyin": "bùmǎn", "english": "dissatisfied; discontented" },
  { "chinese": "不如", "traditional": "不如", "pinyin": "bùrú", "english": "not as good as; inferior to" },
  { "chinese": "不少", "traditional": "不少", "pinyin": "bùshǎo", "english": "quite a lot; many" },
  { "chinese": "不同", "traditional": "不同", "pinyin": "bùtóng", "english": "different; distinct" },
  { "chinese": "不行", "traditional": "不行", "pinyin": "bùxíng", "english": "won't do; not acceptable" },
  { "chinese": "不一定", "traditional": "不一定", "pinyin": "bùyīdìng", "english": "not necessarily; uncertain" },
  { "chinese": "不一会儿", "traditional": "不一會兒", "pinyin": "bùyīhuìr", "english": "in a moment; soon" },
  { "chinese": "部分", "traditional": "部分", "pinyin": "bùfen", "english": "part; portion; section" },
  { "chinese": "才", "traditional": "才", "pinyin": "cái", "english": "only; just; only then" },
  { "chinese": "菜单", "traditional": "菜單", "pinyin": "càidān", "english": "menu" },
  { "chinese": "参观", "traditional": "參觀", "pinyin": "cānguān", "english": "to visit; to tour" },
  { "chinese": "参加", "traditional": "參加", "pinyin": "cānjiā", "english": "to participate; to join" },
  { "chinese": "草", "traditional": "草", "pinyin": "cǎo", "english": "grass; rough draft" },
  { "chinese": "草地", "traditional": "草地", "pinyin": "cǎodì", "english": "grassland; lawn" },
  { "chinese": "层", "traditional": "層", "pinyin": "céng", "english": "layer; floor; level" },
  { "chinese": "查", "traditional": "查", "pinyin": "chá", "english": "to check; to examine; to investigate" },
  { "chinese": "差不多", "traditional": "差不多", "pinyin": "chàbuduō", "english": "almost; nearly; about the same" },
  { "chinese": "长", "traditional": "長", "pinyin": "cháng", "english": "long" },
  { "chinese": "常见", "traditional": "常見", "pinyin": "chángjiàn", "english": "common; frequently seen" },
  { "chinese": "常用", "traditional": "常用", "pinyin": "chángyòng", "english": "commonly used" },
  { "chinese": "场", "traditional": "場", "pinyin": "chǎng", "english": "field; site; place" },
  { "chinese": "超过", "traditional": "超過", "pinyin": "chāoguò", "english": "to exceed; to surpass" },
  { "chinese": "超市", "traditional": "超市", "pinyin": "chāoshì", "english": "supermarket" },
  { "chinese": "车辆", "traditional": "車輛", "pinyin": "chēliàng", "english": "vehicle" },
  { "chinese": "称", "traditional": "稱", "pinyin": "chēng", "english": "to call; to address as" },
  { "chinese": "成", "traditional": "成", "pinyin": "chéng", "english": "to become; to accomplish" },
  { "chinese": "成绩", "traditional": "成績", "pinyin": "chéngjì", "english": "achievement; grade; result" },
  { "chinese": "成为", "traditional": "成為", "pinyin": "chéngwéi", "english": "to become; to turn into" },
  { "chinese": "重复", "traditional": "重複", "pinyin": "chóngfù", "english": "to repeat; repetition" },
  { "chinese": "重新", "traditional": "重新", "pinyin": "chóngxīn", "english": "again; anew; re-" },
  { "chinese": "出发", "traditional": "出發", "pinyin": "chūfā", "english": "to set out; to depart" },
  { "chinese": "出国", "traditional": "出國", "pinyin": "chūguó", "english": "to go abroad" },
  { "chinese": "出口", "traditional": "出口", "pinyin": "chūkǒu", "english": "exit; export" },
  { "chinese": "出门", "traditional": "出門", "pinyin": "chūmén", "english": "to go out; to leave home" },
  { "chinese": "出生", "traditional": "出生", "pinyin": "chūshēng", "english": "to be born; birth" },
  { "chinese": "出现", "traditional": "出現", "pinyin": "chūxiàn", "english": "to appear; to emerge" },
  { "chinese": "出院", "traditional": "出院", "pinyin": "chūyuàn", "english": "to leave hospital; discharge" },
  { "chinese": "出租", "traditional": "出租", "pinyin": "chūzū", "english": "to rent out; for rent" },
  { "chinese": "出租车", "traditional": "出租車", "pinyin": "chūzūchē", "english": "taxi; cab" },
  { "chinese": "船", "traditional": "船", "pinyin": "chuán", "english": "boat; ship" },
  { "chinese": "吹", "traditional": "吹", "pinyin": "chuī", "english": "to blow; to boast" },
  { "chinese": "春节", "traditional": "春節", "pinyin": "chūnjié", "english": "Spring Festival; Chinese New Year" },
  { "chinese": "春天", "traditional": "春天", "pinyin": "chūntiān", "english": "spring" },
  { "chinese": "词", "traditional": "詞", "pinyin": "cí", "english": "word; term" },
  { "chinese": "词典", "traditional": "詞典", "pinyin": "cídiǎn", "english": "dictionary" },
  { "chinese": "词语", "traditional": "詞語", "pinyin": "cíyǔ", "english": "word; term; expression" },
  { "chinese": "从小", "traditional": "從小", "pinyin": "cóngxiǎo", "english": "from childhood; since young" },
  { "chinese": "答应", "traditional": "答應", "pinyin": "dāying", "english": "to agree; to promise" },
  { "chinese": "打工", "traditional": "打工", "pinyin": "dǎgōng", "english": "to work; to have a job" },
  { "chinese": "打算", "traditional": "打算", "pinyin": "dǎsuàn", "english": "to plan; plan; intention" },
  { "chinese": "打印", "traditional": "打印", "pinyin": "dǎyìn", "english": "to print" },
  { "chinese": "大部分", "traditional": "大部分", "pinyin": "dàbùfen", "english": "most; majority" },
  { "chinese": "大大", "traditional": "大大", "pinyin": "dàdà", "english": "greatly; enormously" },
  { "chinese": "大多数", "traditional": "大多數", "pinyin": "dàduōshù", "english": "most; majority" },
  { "chinese": "大海", "traditional": "大海", "pinyin": "dàhǎi", "english": "sea; ocean" },
  { "chinese": "大家", "traditional": "大家", "pinyin": "dàjiā", "english": "everyone; everybody" },
  { "chinese": "大量", "traditional": "大量", "pinyin": "dàliàng", "english": "large quantity; a lot" },
  { "chinese": "大门", "traditional": "大門", "pinyin": "dàmén", "english": "main gate; entrance" },
  { "chinese": "大人", "traditional": "大人", "pinyin": "dàrén", "english": "adult; grown-up" },
  { "chinese": "大声", "traditional": "大聲", "pinyin": "dàshēng", "english": "loud; loudly" },
  { "chinese": "大小", "traditional": "大小", "pinyin": "dàxiǎo", "english": "size; dimension" },
  { "chinese": "大衣", "traditional": "大衣", "pinyin": "dàyī", "english": "overcoat; coat" },
  { "chinese": "大自然", "traditional": "大自然", "pinyin": "dàzìrán", "english": "nature" },
  { "chinese": "带", "traditional": "帶", "pinyin": "dài", "english": "to bring; to carry; belt" },
  { "chinese": "带来", "traditional": "帶來", "pinyin": "dàilái", "english": "to bring; to cause" },
  { "chinese": "单位", "traditional": "單位", "pinyin": "dānwèi", "english": "unit; organization; workplace" },
  { "chinese": "但", "traditional": "但", "pinyin": "dàn", "english": "but; however" },
  { "chinese": "但是", "traditional": "但是", "pinyin": "dànshì", "english": "but; however" },
  { "chinese": "蛋", "traditional": "蛋", "pinyin": "dàn", "english": "egg" },
  { "chinese": "当", "traditional": "當", "pinyin": "dāng", "english": "when; at the time of" },
  { "chinese": "当时", "traditional": "當時", "pinyin": "dāngshí", "english": "at that time; then" },
  { "chinese": "倒", "traditional": "倒", "pinyin": "dǎo", "english": "to fall; to collapse" },
  { "chinese": "到处", "traditional": "到處", "pinyin": "dàochù", "english": "everywhere; all over" },
  { "chinese": "倒", "traditional": "倒", "pinyin": "dào", "english": "on the contrary; instead" },
  { "chinese": "道", "traditional": "道", "pinyin": "dào", "english": "road; way; path" },
  { "chinese": "道理", "traditional": "道理", "pinyin": "dàolǐ", "english": "reason; principle; truth" },
  { "chinese": "道路", "traditional": "道路", "pinyin": "dàolù", "english": "road; path; way" },
  { "chinese": "得", "traditional": "得", "pinyin": "dé", "english": "to get; to obtain" },
  { "chinese": "得出", "traditional": "得出", "pinyin": "déchū", "english": "to reach; to arrive at" },
  { "chinese": "的话", "traditional": "的話", "pinyin": "dehuà", "english": "if; in case" },
  { "chinese": "得", "traditional": "得", "pinyin": "de", "english": "auxiliary word (potential complement)" },
  { "chinese": "灯", "traditional": "燈", "pinyin": "dēng", "english": "lamp; light" },
  { "chinese": "等", "traditional": "等", "pinyin": "děng", "english": "etc.; and so on; to wait" },
  { "chinese": "等到", "traditional": "等到", "pinyin": "děngdào", "english": "to wait until; by the time" },
  { "chinese": "等于", "traditional": "等於", "pinyin": "děngyú", "english": "to equal; to be equivalent to" },
  { "chinese": "低", "traditional": "低", "pinyin": "dī", "english": "low; short" },
  { "chinese": "地球", "traditional": "地球", "pinyin": "dìqiú", "english": "earth; globe" },
  { "chinese": "地铁", "traditional": "地鐵", "pinyin": "dìtiě", "english": "subway; metro" },
  { "chinese": "地铁站", "traditional": "地鐵站", "pinyin": "dìtiězhàn", "english": "subway station" },
  { "chinese": "点头", "traditional": "點頭", "pinyin": "diǎntóu", "english": "to nod" },
  { "chinese": "店", "traditional": "店", "pinyin": "diàn", "english": "shop; store" },
  { "chinese": "掉", "traditional": "掉", "pinyin": "diào", "english": "to fall; to drop; to lose" },
  { "chinese": "东北", "traditional": "東北", "pinyin": "dōngběi", "english": "northeast" },
  { "chinese": "东方", "traditional": "東方", "pinyin": "dōngfāng", "english": "east; the Orient" },
  { "chinese": "东南", "traditional": "東南", "pinyin": "dōngnán", "english": "southeast" },
  { "chinese": "冬天", "traditional": "冬天", "pinyin": "dōngtiān", "english": "winter" },
  { "chinese": "懂", "traditional": "懂", "pinyin": "dǒng", "english": "to understand; to know" },
  { "chinese": "懂得", "traditional": "懂得", "pinyin": "dǒngde", "english": "to understand; to know how to" },
  { "chinese": "动物", "traditional": "動物", "pinyin": "dòngwù", "english": "animal" },
  { "chinese": "动物园", "traditional": "動物園", "pinyin": "dòngwùyuán", "english": "zoo" },
  { "chinese": "读音", "traditional": "讀音", "pinyin": "dúyīn", "english": "pronunciation" },
  { "chinese": "度", "traditional": "度", "pinyin": "dù", "english": "degree; to spend (time)" },
  { "chinese": "短", "traditional": "短", "pinyin": "duǎn", "english": "short" },
  { "chinese": "短信", "traditional": "短信", "pinyin": "duǎnxìn", "english": "text message; SMS" },
  { "chinese": "段", "traditional": "段", "pinyin": "duàn", "english": "section; paragraph; period" },
  { "chinese": "队", "traditional": "隊", "pinyin": "duì", "english": "team; queue" },
  { "chinese": "队长", "traditional": "隊長", "pinyin": "duìzhǎng", "english": "team leader; captain" },
  { "chinese": "对", "traditional": "對", "pinyin": "duì", "english": "toward; correct; to face" },
  { "chinese": "对话", "traditional": "對話", "pinyin": "duìhuà", "english": "dialogue; conversation" },
  { "chinese": "对面", "traditional": "對面", "pinyin": "duìmiàn", "english": "opposite; across from" },
  { "chinese": "多", "traditional": "多", "pinyin": "duō", "english": "much more; how (adverb)" },
  { "chinese": "多久", "traditional": "多久", "pinyin": "duōjiǔ", "english": "how long; how much time" },
  { "chinese": "多么", "traditional": "多麼", "pinyin": "duōme", "english": "how; what; so" },
  { "chinese": "多数", "traditional": "多數", "pinyin": "duōshù", "english": "majority; most" },
  { "chinese": "多云", "traditional": "多雲", "pinyin": "duōyún", "english": "cloudy; overcast" },
  { "chinese": "而且", "traditional": "而且", "pinyin": "érqiě", "english": "and; moreover; furthermore" },
  { "chinese": "发", "traditional": "發", "pinyin": "fā", "english": "to send; to emit; to develop" },
  { "chinese": "发现", "traditional": "發現", "pinyin": "fāxiàn", "english": "to discover; to find" },
  { "chinese": "饭馆", "traditional": "飯館", "pinyin": "fànguǎn", "english": "restaurant" },
  { "chinese": "方便", "traditional": "方便", "pinyin": "fāngbiàn", "english": "convenient; handy" },
  { "chinese": "方便面", "traditional": "方便麵", "pinyin": "fāngbiànmiàn", "english": "instant noodles" },
  { "chinese": "方法", "traditional": "方法", "pinyin": "fāngfǎ", "english": "method; way; means" },
  { "chinese": "方面", "traditional": "方面", "pinyin": "fāngmiàn", "english": "aspect; respect; area" },
  { "chinese": "方向", "traditional": "方向", "pinyin": "fāngxiàng", "english": "direction; orientation" },
  { "chinese": "放下", "traditional": "放下", "pinyin": "fàngxià", "english": "to put down; to lay down" },
  { "chinese": "放心", "traditional": "放心", "pinyin": "fàngxīn", "english": "to be at ease; don't worry" },
  { "chinese": "分", "traditional": "分", "pinyin": "fēn", "english": "to divide; to separate" },
  { "chinese": "分开", "traditional": "分開", "pinyin": "fēnkāi", "english": "to separate; to part" },
  { "chinese": "分数", "traditional": "分數", "pinyin": "fēnshù", "english": "score; grade; fraction" },
  { "chinese": "分钟", "traditional": "分鐘", "pinyin": "fēnzhōng", "english": "minute" },
  { "chinese": "份", "traditional": "份", "pinyin": "fèn", "english": "portion; share; copy" },
  { "chinese": "封", "traditional": "封", "pinyin": "fēng", "english": "measure word for letters" },
  { "chinese": "服务", "traditional": "服務", "pinyin": "fúwù", "english": "service; to serve" },
  { "chinese": "复习", "traditional": "複習", "pinyin": "fùxí", "english": "to review; to revise" },
  { "chinese": "该", "traditional": "該", "pinyin": "gāi", "english": "should; ought to" },
  { "chinese": "改", "traditional": "改", "pinyin": "gǎi", "english": "to change; to alter; to correct" },
  { "chinese": "改变", "traditional": "改變", "pinyin": "gǎibiàn", "english": "to change; to transform" },
  { "chinese": "干杯", "traditional": "乾杯", "pinyin": "gānbēi", "english": "cheers; bottoms up" },
  { "chinese": "感到", "traditional": "感到", "pinyin": "gǎndào", "english": "to feel; to sense" },
  { "chinese": "感动", "traditional": "感動", "pinyin": "gǎndòng", "english": "to move; to touch emotionally" },
  { "chinese": "感觉", "traditional": "感覺", "pinyin": "gǎnjué", "english": "to feel; feeling; sensation" },
  { "chinese": "感谢", "traditional": "感謝", "pinyin": "gǎnxiè", "english": "to thank; gratitude" },
  { "chinese": "干活儿", "traditional": "幹活兒", "pinyin": "gànhuór", "english": "to work; to do manual work" },
  { "chinese": "刚", "traditional": "剛", "pinyin": "gāng", "english": "just; just now; hard" },
  { "chinese": "刚才", "traditional": "剛才", "pinyin": "gāngcái", "english": "just now; a moment ago" },
  { "chinese": "刚刚", "traditional": "剛剛", "pinyin": "gānggāng", "english": "just; just now" },
  { "chinese": "高级", "traditional": "高級", "pinyin": "gāojí", "english": "high-level; advanced; senior" },
  { "chinese": "高中", "traditional": "高中", "pinyin": "gāozhōng", "english": "senior high school" },
  { "chinese": "个子", "traditional": "個子", "pinyin": "gèzi", "english": "height; stature" },
  { "chinese": "更", "traditional": "更", "pinyin": "gèng", "english": "more; even more" },
  { "chinese": "公共汽车", "traditional": "公共汽車", "pinyin": "gōnggòngqìchē", "english": "public bus" },
  { "chinese": "公交车", "traditional": "公交車", "pinyin": "gōngjiāochē", "english": "public bus" },
  { "chinese": "公斤", "traditional": "公斤", "pinyin": "gōngjīn", "english": "kilogram" },
  { "chinese": "公里", "traditional": "公里", "pinyin": "gōnglǐ", "english": "kilometer" },
  { "chinese": "公路", "traditional": "公路", "pinyin": "gōnglù", "english": "highway; main road" },
  { "chinese": "公平", "traditional": "公平", "pinyin": "gōngpíng", "english": "fair; just; impartial" },
  { "chinese": "公司", "traditional": "公司", "pinyin": "gōngsī", "english": "company; corporation" },
  { "chinese": "公园", "traditional": "公園", "pinyin": "gōngyuán", "english": "park; public garden" },
  { "chinese": "狗", "traditional": "狗", "pinyin": "gǒu", "english": "dog" },
  { "chinese": "够", "traditional": "夠", "pinyin": "gòu", "english": "enough; sufficient" },
  { "chinese": "故事", "traditional": "故事", "pinyin": "gùshi", "english": "story; tale" },
  { "chinese": "故意", "traditional": "故意", "pinyin": "gùyì", "english": "on purpose; deliberately" },
  { "chinese": "顾客", "traditional": "顧客", "pinyin": "gùkè", "english": "customer; client" },
  { "chinese": "关机", "traditional": "關機", "pinyin": "guānjī", "english": "to turn off; to shut down" },
  { "chinese": "关心", "traditional": "關心", "pinyin": "guānxīn", "english": "to care about; to be concerned" },
  { "chinese": "观点", "traditional": "觀點", "pinyin": "guāndiǎn", "english": "viewpoint; opinion" },
  { "chinese": "广场", "traditional": "廣場", "pinyin": "guǎngchǎng", "english": "square; plaza" },
  { "chinese": "广告", "traditional": "廣告", "pinyin": "guǎnggào", "english": "advertisement" },
  { "chinese": "国际", "traditional": "國際", "pinyin": "guójì", "english": "international" },
  { "chinese": "过来", "traditional": "過來", "pinyin": "guòlái", "english": "to come over; to come here" },
  { "chinese": "过年", "traditional": "過年", "pinyin": "guònián", "english": "to celebrate New Year" },
  { "chinese": "过去", "traditional": "過去", "pinyin": "guòqù", "english": "to go over; past" },
  { "chinese": "过", "traditional": "過", "pinyin": "guò", "english": "to pass; to cross; to spend" },
  { "chinese": "海", "traditional": "海", "pinyin": "hǎi", "english": "sea; ocean" },
  { "chinese": "海边", "traditional": "海邊", "pinyin": "hǎibiān", "english": "seaside; seashore" },
  { "chinese": "喊", "traditional": "喊", "pinyin": "hǎn", "english": "to shout; to call out" },
  { "chinese": "好", "traditional": "好", "pinyin": "hǎo", "english": "well; good (adverb)" },
  { "chinese": "好处", "traditional": "好處", "pinyin": "hǎochu", "english": "benefit; advantage" },
  { "chinese": "好多", "traditional": "好多", "pinyin": "hǎoduō", "english": "many; a lot of" },
  { "chinese": "好久", "traditional": "好久", "pinyin": "hǎojiǔ", "english": "for a long time" },
  { "chinese": "好人", "traditional": "好人", "pinyin": "hǎorén", "english": "good person" },
  { "chinese": "好事", "traditional": "好事", "pinyin": "hǎoshì", "english": "good deed; good thing" },
  { "chinese": "好像", "traditional": "好像", "pinyin": "hǎoxiàng", "english": "to seem like; as if" },
  { "chinese": "合适", "traditional": "合適", "pinyin": "héshì", "english": "suitable; appropriate" },
  { "chinese": "河", "traditional": "河", "pinyin": "hé", "english": "river" },
  { "chinese": "黑", "traditional": "黑", "pinyin": "hēi", "english": "black; dark" },
  { "chinese": "黑板", "traditional": "黑板", "pinyin": "hēibǎn", "english": "blackboard" },
  { "chinese": "黑色", "traditional": "黑色", "pinyin": "hēisè", "english": "black; black color" },
  { "chinese": "红", "traditional": "紅", "pinyin": "hóng", "english": "red" },
  { "chinese": "红色", "traditional": "紅色", "pinyin": "hóngsè", "english": "red; red color" },
  { "chinese": "后来", "traditional": "後來", "pinyin": "hòulái", "english": "later; afterwards" },
  { "chinese": "忽然", "traditional": "忽然", "pinyin": "hūrán", "english": "suddenly; all of a sudden" },
  { "chinese": "湖", "traditional": "湖", "pinyin": "hú", "english": "lake" },
  { "chinese": "护照", "traditional": "護照", "pinyin": "hùzhào", "english": "passport" },
  { "chinese": "花", "traditional": "花", "pinyin": "huā", "english": "to spend; to cost" },
  { "chinese": "花园", "traditional": "花園", "pinyin": "huāyuán", "english": "garden" },
  { "chinese": "画", "traditional": "畫", "pinyin": "huà", "english": "painting; to paint" },
  { "chinese": "画家", "traditional": "畫家", "pinyin": "huàjiā", "english": "painter; artist" },
  { "chinese": "画儿", "traditional": "畫兒", "pinyin": "huàr", "english": "painting; picture" },
  { "chinese": "坏处", "traditional": "壞處", "pinyin": "huàichu", "english": "disadvantage; harm" },
  { "chinese": "坏人", "traditional": "壞人", "pinyin": "huàirén", "english": "bad person; villain" },
  { "chinese": "欢迎", "traditional": "歡迎", "pinyin": "huānyíng", "english": "to welcome" },
  { "chinese": "换", "traditional": "換", "pinyin": "huàn", "english": "to change; to exchange" },
  { "chinese": "黄", "traditional": "黃", "pinyin": "huáng", "english": "yellow" },
  { "chinese": "黄色", "traditional": "黃色", "pinyin": "huángsè", "english": "yellow; yellow color" },
  { "chinese": "回", "traditional": "回", "pinyin": "huí", "english": "time; round (measure word)" },
  { "chinese": "回国", "traditional": "回國", "pinyin": "huíguó", "english": "to return to one's country" },
  { "chinese": "会", "traditional": "會", "pinyin": "huì", "english": "meeting; conference" },
  { "chinese": "活动", "traditional": "活動", "pinyin": "huódòng", "english": "activity; event" },
  { "chinese": "或", "traditional": "或", "pinyin": "huò", "english": "or; either" },
  { "chinese": "或者", "traditional": "或者", "pinyin": "huòzhě", "english": "or; either... or" },
  { "chinese": "机会", "traditional": "機會", "pinyin": "jīhuì", "english": "opportunity; chance" },
  { "chinese": "鸡", "traditional": "雞", "pinyin": "jī", "english": "chicken" },
  { "chinese": "级", "traditional": "級", "pinyin": "jí", "english": "level; grade; rank" },
  { "chinese": "急", "traditional": "急", "pinyin": "jí", "english": "urgent; anxious; hurried" },
  { "chinese": "计划", "traditional": "計劃", "pinyin": "jìhuà", "english": "plan; to plan" },
  { "chinese": "计算机", "traditional": "計算機", "pinyin": "jìsuànjī", "english": "computer" },
  { "chinese": "加", "traditional": "加", "pinyin": "jiā", "english": "to add; to increase" },
  { "chinese": "加油", "traditional": "加油", "pinyin": "jiāyóu", "english": "to refuel; come on; cheer up" },
  { "chinese": "家", "traditional": "家", "pinyin": "jiā", "english": "suffix for specialists" },
  { "chinese": "家庭", "traditional": "家庭", "pinyin": "jiātíng", "english": "family; household" },
  { "chinese": "家长", "traditional": "家長", "pinyin": "jiāzhǎng", "english": "parent; head of family" },
  { "chinese": "假", "traditional": "假", "pinyin": "jiǎ", "english": "fake; false; artificial" },
  { "chinese": "假期", "traditional": "假期", "pinyin": "jiàqī", "english": "holiday; vacation" },
  { "chinese": "检查", "traditional": "檢查", "pinyin": "jiǎnchá", "english": "to check; to examine" },
  { "chinese": "见到", "traditional": "見到", "pinyin": "jiàndào", "english": "to see; to meet" },
  { "chinese": "见过", "traditional": "見過", "pinyin": "jiànguò", "english": "to have seen; to have met" },
  { "chinese": "件", "traditional": "件", "pinyin": "jiàn", "english": "piece; item (measure word)" },
  { "chinese": "健康", "traditional": "健康", "pinyin": "jiànkāng", "english": "healthy; health" },
  { "chinese": "讲", "traditional": "講", "pinyin": "jiǎng", "english": "to speak; to tell" },
  { "chinese": "讲话", "traditional": "講話", "pinyin": "jiǎnghuà", "english": "to speak; to talk" },
  { "chinese": "交", "traditional": "交", "pinyin": "jiāo", "english": "to hand over; to deliver" },
  { "chinese": "交给", "traditional": "交給", "pinyin": "jiāogěi", "english": "to hand over to" },
  { "chinese": "交朋友", "traditional": "交朋友", "pinyin": "jiāopéngyǒu", "english": "to make friends" },
  { "chinese": "交通", "traditional": "交通", "pinyin": "jiāotōng", "english": "traffic; transportation" },
  { "chinese": "角", "traditional": "角", "pinyin": "jiǎo", "english": "corner; angle; horn" },
  { "chinese": "角度", "traditional": "角度", "pinyin": "jiǎodù", "english": "angle; perspective" },
  { "chinese": "饺子", "traditional": "餃子", "pinyin": "jiǎozi", "english": "dumpling" },
  { "chinese": "脚", "traditional": "腳", "pinyin": "jiǎo", "english": "foot" },
  { "chinese": "叫作", "traditional": "叫作", "pinyin": "jiàozuò", "english": "to be called; to be known as" },
  { "chinese": "教师", "traditional": "教師", "pinyin": "jiàoshī", "english": "teacher" },
  { "chinese": "教室", "traditional": "教室", "pinyin": "jiàoshì", "english": "classroom" },
  { "chinese": "教学", "traditional": "教學", "pinyin": "jiàoxué", "english": "teaching; education" },
  { "chinese": "教育", "traditional": "教育", "pinyin": "jiàoyù", "english": "education; to educate" },
  { "chinese": "接", "traditional": "接", "pinyin": "jiē", "english": "to receive; to pick up" },
  { "chinese": "接到", "traditional": "接到", "pinyin": "jiēdào", "english": "to receive; to get" },
  { "chinese": "接受", "traditional": "接受", "pinyin": "jiēshòu", "english": "to accept; to receive" },
  { "chinese": "接下来", "traditional": "接下來", "pinyin": "jiēxiàlái", "english": "next; following" },
  { "chinese": "接着", "traditional": "接著", "pinyin": "jiēzhe", "english": "then; next; to continue" },
  { "chinese": "街", "traditional": "街", "pinyin": "jiē", "english": "street" },
  { "chinese": "节", "traditional": "節", "pinyin": "jié", "english": "festival; section; measure word" },
  { "chinese": "节目", "traditional": "節目", "pinyin": "jiémù", "english": "program; show" },
  { "chinese": "节日", "traditional": "節日", "pinyin": "jiérì", "english": "festival; holiday" },
  { "chinese": "结果", "traditional": "結果", "pinyin": "jiéguǒ", "english": "result; outcome" },
  { "chinese": "借", "traditional": "借", "pinyin": "jiè", "english": "to borrow; to lend" },
  { "chinese": "斤", "traditional": "斤", "pinyin": "jīn", "english": "catty (unit of weight)" },
  { "chinese": "今后", "traditional": "今後", "pinyin": "jīnhòu", "english": "from now on; in future" },
  { "chinese": "进入", "traditional": "進入", "pinyin": "jìnrù", "english": "to enter; to go into" },
  { "chinese": "进行", "traditional": "進行", "pinyin": "jìnxíng", "english": "to carry out; to conduct" },
  { "chinese": "近", "traditional": "近", "pinyin": "jìn", "english": "near; close" },
  { "chinese": "经常", "traditional": "經常", "pinyin": "jīngcháng", "english": "often; frequently" },
  { "chinese": "经过", "traditional": "經過", "pinyin": "jīngguò", "english": "to pass through; after" },
  { "chinese": "经理", "traditional": "經理", "pinyin": "jīnglǐ", "english": "manager" },
  { "chinese": "酒", "traditional": "酒", "pinyin": "jiǔ", "english": "alcohol; wine; liquor" },
  { "chinese": "酒店", "traditional": "酒店", "pinyin": "jiǔdiàn", "english": "hotel" },
  { "chinese": "就要", "traditional": "就要", "pinyin": "jiùyào", "english": "to be about to; soon" },
  { "chinese": "举", "traditional": "舉", "pinyin": "jǔ", "english": "to lift; to raise; to hold" },
  { "chinese": "举手", "traditional": "舉手", "pinyin": "jǔshǒu", "english": "to raise one's hand" },
  { "chinese": "举行", "traditional": "舉行", "pinyin": "jǔxíng", "english": "to hold; to conduct" },
  { "chinese": "句", "traditional": "句", "pinyin": "jù", "english": "sentence; measure word" },
  { "chinese": "句子", "traditional": "句子", "pinyin": "jùzi", "english": "sentence" },
  { "chinese": "卡", "traditional": "卡", "pinyin": "kǎ", "english": "card" },
  { "chinese": "开机", "traditional": "開機", "pinyin": "kāijī", "english": "to start up; to turn on" },
  { "chinese": "开心", "traditional": "開心", "pinyin": "kāixīn", "english": "happy; joyful" },
  { "chinese": "开学", "traditional": "開學", "pinyin": "kāixué", "english": "school starts; new term begins" },
  { "chinese": "看法", "traditional": "看法", "pinyin": "kànfǎ", "english": "view; opinion" },
  { "chinese": "考生", "traditional": "考生", "pinyin": "kǎoshēng", "english": "test taker; examinee" },
  { "chinese": "靠", "traditional": "靠", "pinyin": "kào", "english": "to lean on; to rely on" },
  { "chinese": "科", "traditional": "科", "pinyin": "kē", "english": "subject; department; branch" },
  { "chinese": "科学", "traditional": "科學", "pinyin": "kēxué", "english": "science; scientific" },
  { "chinese": "可爱", "traditional": "可愛", "pinyin": "kěài", "english": "cute; lovely" },
  { "chinese": "可能", "traditional": "可能", "pinyin": "kěnéng", "english": "possible; maybe" },
  { "chinese": "可怕", "traditional": "可怕", "pinyin": "kěpà", "english": "terrible; frightening" },
  { "chinese": "可是", "traditional": "可是", "pinyin": "kěshì", "english": "but; however" },
  { "chinese": "可以", "traditional": "可以", "pinyin": "kěyǐ", "english": "can; may; okay" },
  { "chinese": "克", "traditional": "克", "pinyin": "kè", "english": "gram" },
  { "chinese": "刻", "traditional": "刻", "pinyin": "kè", "english": "quarter hour; moment" },
  { "chinese": "客人", "traditional": "客人", "pinyin": "kèrén", "english": "guest; visitor" },
  { "chinese": "课堂", "traditional": "課堂", "pinyin": "kètáng", "english": "classroom; class" },
  { "chinese": "空气", "traditional": "空氣", "pinyin": "kōngqì", "english": "air; atmosphere" },
  { "chinese": "哭", "traditional": "哭", "pinyin": "kū", "english": "to cry; to weep" },
  { "chinese": "快餐", "traditional": "快餐", "pinyin": "kuàicān", "english": "fast food" },
  { "chinese": "快点儿", "traditional": "快點兒", "pinyin": "kuàidiǎnr", "english": "hurry up; quickly" },
  { "chinese": "快乐", "traditional": "快樂", "pinyin": "kuàilè", "english": "happy; joyful" },
  { "chinese": "快要", "traditional": "快要", "pinyin": "kuàiyào", "english": "soon; about to" },
  { "chinese": "筷子", "traditional": "筷子", "pinyin": "kuàizi", "english": "chopsticks" },
  { "chinese": "拉", "traditional": "拉", "pinyin": "lā", "english": "to pull; to drag" },
  { "chinese": "来自", "traditional": "來自", "pinyin": "láizì", "english": "to come from; to originate from" },
  { "chinese": "蓝", "traditional": "藍", "pinyin": "lán", "english": "blue" },
  { "chinese": "蓝色", "traditional": "藍色", "pinyin": "lánsè", "english": "blue; blue color" },
  { "chinese": "篮球", "traditional": "籃球", "pinyin": "lánqiú", "english": "basketball" },
  { "chinese": "老", "traditional": "老", "pinyin": "lǎo", "english": "always; constantly (adverb)" },
  { "chinese": "老", "traditional": "老", "pinyin": "lǎo", "english": "old (prefix for names)" },
  { "chinese": "老年", "traditional": "老年", "pinyin": "lǎonián", "english": "old age; elderly" },
  { "chinese": "老朋友", "traditional": "老朋友", "pinyin": "lǎopéngyǒu", "english": "old friend" },
  { "chinese": "老是", "traditional": "老是", "pinyin": "lǎoshì", "english": "always; constantly" },
  { "chinese": "离", "traditional": "離", "pinyin": "lí", "english": "to leave; away from" },
  { "chinese": "离开", "traditional": "離開", "pinyin": "líkāi", "english": "to leave; to depart" },
  { "chinese": "礼物", "traditional": "禮物", "pinyin": "lǐwù", "english": "gift; present" },
  { "chinese": "里头", "traditional": "裡頭", "pinyin": "lǐtou", "english": "inside; within" },
  { "chinese": "理想", "traditional": "理想", "pinyin": "lǐxiǎng", "english": "ideal; dream" },
  { "chinese": "例如", "traditional": "例如", "pinyin": "lìrú", "english": "for example; such as" },
  { "chinese": "例子", "traditional": "例子", "pinyin": "lìzi", "english": "example; instance" },
  { "chinese": "脸", "traditional": "臉", "pinyin": "liǎn", "english": "face" },
  { "chinese": "练", "traditional": "練", "pinyin": "liàn", "english": "to practice; to train" },
  { "chinese": "练习", "traditional": "練習", "pinyin": "liànxí", "english": "to practice; exercise" },
  { "chinese": "凉", "traditional": "涼", "pinyin": "liáng", "english": "cool; cold" },
  { "chinese": "凉快", "traditional": "涼快", "pinyin": "liángkuai", "english": "cool and refreshing" },
  { "chinese": "两", "traditional": "兩", "pinyin": "liǎng", "english": "tael (unit of weight)" },
  { "chinese": "亮", "traditional": "亮", "pinyin": "liàng", "english": "bright; light" },
  { "chinese": "辆", "traditional": "輛", "pinyin": "liàng", "english": "measure word for vehicles" },
  { "chinese": "零下", "traditional": "零下", "pinyin": "língxià", "english": "below zero; sub-zero" },
  { "chinese": "留", "traditional": "留", "pinyin": "liú", "english": "to stay; to remain; to keep" },
  { "chinese": "留下", "traditional": "留下", "pinyin": "liúxià", "english": "to leave behind; to stay" },
  { "chinese": "留学生", "traditional": "留學生", "pinyin": "liúxuéshēng", "english": "international student" },
  { "chinese": "流", "traditional": "流", "pinyin": "liú", "english": "to flow; to spread" },
  { "chinese": "流利", "traditional": "流利", "pinyin": "liúlì", "english": "fluent; smooth" },
  { "chinese": "流行", "traditional": "流行", "pinyin": "liúxíng", "english": "popular; fashionable" },
  { "chinese": "路边", "traditional": "路邊", "pinyin": "lùbiān", "english": "roadside; by the road" },
  { "chinese": "旅客", "traditional": "旅客", "pinyin": "lǚkè", "english": "passenger; traveler" },
  { "chinese": "旅行", "traditional": "旅行", "pinyin": "lǚxíng", "english": "to travel; trip" },
  { "chinese": "旅游", "traditional": "旅遊", "pinyin": "lǚyóu", "english": "tourism; to tour" },
  { "chinese": "绿", "traditional": "綠", "pinyin": "lǜ", "english": "green" },
  { "chinese": "绿色", "traditional": "綠色", "pinyin": "lǜsè", "english": "green; green color" },
  { "chinese": "卖", "traditional": "賣", "pinyin": "mài", "english": "to sell" },
  { "chinese": "满", "traditional": "滿", "pinyin": "mǎn", "english": "full; filled" },
  { "chinese": "满意", "traditional": "滿意", "pinyin": "mǎnyì", "english": "satisfied; pleased" },
  { "chinese": "猫", "traditional": "貓", "pinyin": "māo", "english": "cat" },
  { "chinese": "米", "traditional": "米", "pinyin": "mǐ", "english": "meter; rice" },
  { "chinese": "面", "traditional": "面", "pinyin": "miàn", "english": "surface; side; aspect" },
  { "chinese": "面", "traditional": "麵", "pinyin": "miàn", "english": "noodles; flour" },
  { "chinese": "面前", "traditional": "面前", "pinyin": "miànqián", "english": "in front of; before" },
  { "chinese": "名", "traditional": "名", "pinyin": "míng", "english": "name; famous" },
  { "chinese": "名称", "traditional": "名稱", "pinyin": "míngchēng", "english": "name; title; designation" },
  { "chinese": "名单", "traditional": "名單", "pinyin": "míngdān", "english": "list; roster" },
  { "chinese": "明星", "traditional": "明星", "pinyin": "míngxīng", "english": "star; celebrity" },
  { "chinese": "目的", "traditional": "目的", "pinyin": "mùdì", "english": "purpose; goal; objective" },
  { "chinese": "拿出", "traditional": "拿出", "pinyin": "náchū", "english": "to take out; to bring out" },
  { "chinese": "拿到", "traditional": "拿到", "pinyin": "nádào", "english": "to get; to obtain" },
  { "chinese": "那", "traditional": "那", "pinyin": "nà", "english": "then; in that case" },
  { "chinese": "那会儿", "traditional": "那會兒", "pinyin": "nàhuìr", "english": "at that time; then" },
  { "chinese": "那么", "traditional": "那麼", "pinyin": "nàme", "english": "so; like that; in that way" },
  { "chinese": "那时候", "traditional": "那時候", "pinyin": "nàshíhou", "english": "at that time; then" },
  { "chinese": "那样", "traditional": "那樣", "pinyin": "nàyàng", "english": "that way; like that" },
  { "chinese": "南方", "traditional": "南方", "pinyin": "nánfāng", "english": "south; southern region" },
  { "chinese": "难过", "traditional": "難過", "pinyin": "nánguò", "english": "sad; upset; difficult" },
  { "chinese": "难看", "traditional": "難看", "pinyin": "nánkàn", "english": "ugly; unsightly" },
  { "chinese": "难受", "traditional": "難受", "pinyin": "nánshòu", "english": "uncomfortable; unwell" },
  { "chinese": "难题", "traditional": "難題", "pinyin": "nántí", "english": "difficult problem; puzzle" },
  { "chinese": "难听", "traditional": "難聽", "pinyin": "nántīng", "english": "unpleasant to hear; harsh" },
  { "chinese": "能够", "traditional": "能夠", "pinyin": "nénggòu", "english": "to be able to; capable of" },
  { "chinese": "年级", "traditional": "年級", "pinyin": "niánjí", "english": "grade; year (in school)" },
  { "chinese": "年轻", "traditional": "年輕", "pinyin": "niánqīng", "english": "young; youthful" },
  { "chinese": "鸟", "traditional": "鳥", "pinyin": "niǎo", "english": "bird" },
  { "chinese": "弄", "traditional": "弄", "pinyin": "nòng", "english": "to do; to make; to handle" },
  { "chinese": "努力", "traditional": "努力", "pinyin": "nǔlì", "english": "to work hard; effort" },
  { "chinese": "爬", "traditional": "爬", "pinyin": "pá", "english": "to climb; to crawl" },
  { "chinese": "爬山", "traditional": "爬山", "pinyin": "páshān", "english": "to climb mountains; hiking" },
  { "chinese": "怕", "traditional": "怕", "pinyin": "pà", "english": "to be afraid; to fear" },
  { "chinese": "排", "traditional": "排", "pinyin": "pái", "english": "row; line; to arrange" },
  { "chinese": "排队", "traditional": "排隊", "pinyin": "páiduì", "english": "to queue; to line up" },
  { "chinese": "排球", "traditional": "排球", "pinyin": "páiqiú", "english": "volleyball" },
  { "chinese": "碰", "traditional": "碰", "pinyin": "pèng", "english": "to touch; to bump into" },
  { "chinese": "碰到", "traditional": "碰到", "pinyin": "pèngdào", "english": "to run into; to encounter" },
  { "chinese": "碰见", "traditional": "碰見", "pinyin": "pèngjiàn", "english": "to meet; to run into" },
  { "chinese": "篇", "traditional": "篇", "pinyin": "piān", "english": "piece; article (measure word)" },
  { "chinese": "便宜", "traditional": "便宜", "pinyin": "piányi", "english": "cheap; inexpensive" },
  { "chinese": "片", "traditional": "片", "pinyin": "piàn", "english": "slice; piece; film" },
  { "chinese": "漂亮", "traditional": "漂亮", "pinyin": "piàoliang", "english": "beautiful; pretty" },
  { "chinese": "平", "traditional": "平", "pinyin": "píng", "english": "flat; level; calm" },
  { "chinese": "平安", "traditional": "平安", "pinyin": "píng'ān", "english": "safe; peaceful" },
  { "chinese": "平常", "traditional": "平常", "pinyin": "píngcháng", "english": "ordinary; usual; normal" },
  { "chinese": "平等", "traditional": "平等", "pinyin": "píngděng", "english": "equal; equality" },
  { "chinese": "平时", "traditional": "平時", "pinyin": "píngshí", "english": "usually; ordinarily" },
  { "chinese": "瓶", "traditional": "瓶", "pinyin": "píng", "english": "bottle" },
  { "chinese": "瓶子", "traditional": "瓶子", "pinyin": "píngzi", "english": "bottle" },
  { "chinese": "普通", "traditional": "普通", "pinyin": "pǔtōng", "english": "ordinary; common; general" },
  { "chinese": "普通话", "traditional": "普通話", "pinyin": "pǔtōnghuà", "english": "Mandarin Chinese" },
  { "chinese": "其他", "traditional": "其他", "pinyin": "qítā", "english": "other; else" },
  { "chinese": "其中", "traditional": "其中", "pinyin": "qízhōng", "english": "among; in which" },
  { "chinese": "骑", "traditional": "騎", "pinyin": "qí", "english": "to ride" },
  { "chinese": "骑车", "traditional": "騎車", "pinyin": "qíchē", "english": "to ride a bike" },
  { "chinese": "起飞", "traditional": "起飛", "pinyin": "qǐfēi", "english": "to take off (airplane)" },
  { "chinese": "气", "traditional": "氣", "pinyin": "qì", "english": "air; gas; breath" },
  { "chinese": "气温", "traditional": "氣溫", "pinyin": "qìwēn", "english": "air temperature" },
  { "chinese": "千", "traditional": "千", "pinyin": "qiān", "english": "thousand" },
  { "chinese": "千克", "traditional": "千克", "pinyin": "qiānkè", "english": "kilogram" },
  { "chinese": "前年", "traditional": "前年", "pinyin": "qiánnián", "english": "the year before last" },
  { "chinese": "墙", "traditional": "牆", "pinyin": "qiáng", "english": "wall" },
  { "chinese": "青年", "traditional": "青年", "pinyin": "qīngnián", "english": "youth; young person" },
  { "chinese": "青少年", "traditional": "青少年", "pinyin": "qīngshàonián", "english": "teenager; adolescent" },
  { "chinese": "轻", "traditional": "輕", "pinyin": "qīng", "english": "light; gentle" },
  { "chinese": "清楚", "traditional": "清楚", "pinyin": "qīngchu", "english": "clear; obvious" },
  { "chinese": "晴", "traditional": "晴", "pinyin": "qíng", "english": "sunny; clear" },
  { "chinese": "晴天", "traditional": "晴天", "pinyin": "qíngtiān", "english": "sunny day; fine weather" },
  { "chinese": "请客", "traditional": "請客", "pinyin": "qǐngkè", "english": "to treat; to invite" },
  { "chinese": "请求", "traditional": "請求", "pinyin": "qǐngqiú", "english": "to request; to ask for" },
  { "chinese": "秋天", "traditional": "秋天", "pinyin": "qiūtiān", "english": "autumn; fall" },
  { "chinese": "求", "traditional": "求", "pinyin": "qiú", "english": "to request; to seek; to beg" },
  { "chinese": "球场", "traditional": "球場", "pinyin": "qiúchǎng", "english": "court; field; stadium" },
  { "chinese": "球队", "traditional": "球隊", "pinyin": "qiúduì", "english": "team" },
  { "chinese": "球鞋", "traditional": "球鞋", "pinyin": "qiúxié", "english": "sneakers; sports shoes" },
  { "chinese": "取", "traditional": "取", "pinyin": "qǔ", "english": "to take; to get; to fetch" },
  { "chinese": "取得", "traditional": "取得", "pinyin": "qǔdé", "english": "to obtain; to achieve" },
  { "chinese": "全", "traditional": "全", "pinyin": "quán", "english": "whole; entire; complete" },
  { "chinese": "全部", "traditional": "全部", "pinyin": "quánbù", "english": "all; entire; whole" },
  { "chinese": "全国", "traditional": "全國", "pinyin": "quánguó", "english": "nationwide; whole country" },
  { "chinese": "全家", "traditional": "全家", "pinyin": "quánjiā", "english": "whole family" },
  { "chinese": "全年", "traditional": "全年", "pinyin": "quánnián", "english": "whole year; all year" },
  { "chinese": "全身", "traditional": "全身", "pinyin": "quánshēn", "english": "whole body" },
  { "chinese": "全体", "traditional": "全體", "pinyin": "quántǐ", "english": "all; entire; whole" },
  { "chinese": "然后", "traditional": "然後", "pinyin": "ránhòu", "english": "then; after that" },
  { "chinese": "让", "traditional": "讓", "pinyin": "ràng", "english": "to let; to allow; to make" },
  { "chinese": "热情", "traditional": "熱情", "pinyin": "rèqíng", "english": "enthusiastic; passionate" },
  { "chinese": "人口", "traditional": "人口", "pinyin": "rénkǒu", "english": "population" },
  { "chinese": "人们", "traditional": "人們", "pinyin": "rénmen", "english": "people" },
  { "chinese": "人数", "traditional": "人數", "pinyin": "rénshù", "english": "number of people" },
  { "chinese": "认为", "traditional": "認為", "pinyin": "rènwéi", "english": "to think; to believe" },
  { "chinese": "日报", "traditional": "日報", "pinyin": "rìbào", "english": "daily newspaper" },
  { "chinese": "日子", "traditional": "日子", "pinyin": "rìzi", "english": "day; date; life" },
  { "chinese": "如果", "traditional": "如果", "pinyin": "rúguǒ", "english": "if; in case" },
  { "chinese": "入口", "traditional": "入口", "pinyin": "rùkǒu", "english": "entrance; entry" },
  { "chinese": "商量", "traditional": "商量", "pinyin": "shāngliang", "english": "to discuss; to consult" },
  { "chinese": "商人", "traditional": "商人", "pinyin": "shāngrén", "english": "businessman; merchant" },
  { "chinese": "上周", "traditional": "上周", "pinyin": "shàngzhōu", "english": "last week" },
  { "chinese": "少数", "traditional": "少數", "pinyin": "shǎoshù", "english": "small number; minority" },
  { "chinese": "少年", "traditional": "少年", "pinyin": "shàonián", "english": "youth; juvenile" },
  { "chinese": "身边", "traditional": "身邊", "pinyin": "shēnbiān", "english": "at one's side; around" },
  { "chinese": "什么样", "traditional": "什麼樣", "pinyin": "shénmeyàng", "english": "what kind; what type" },
  { "chinese": "生", "traditional": "生", "pinyin": "shēng", "english": "to give birth; to be born" },
  { "chinese": "生词", "traditional": "生詞", "pinyin": "shēngcí", "english": "new word; vocabulary" },
  { "chinese": "生活", "traditional": "生活", "pinyin": "shēnghuó", "english": "life; to live" },
  { "chinese": "声音", "traditional": "聲音", "pinyin": "shēngyīn", "english": "sound; voice" },
  { "chinese": "省", "traditional": "省", "pinyin": "shěng", "english": "province" },
  { "chinese": "省", "traditional": "省", "pinyin": "shěng", "english": "to save; to economize" },
  { "chinese": "十分", "traditional": "十分", "pinyin": "shífēn", "english": "very; extremely; fully" },
  { "chinese": "实际", "traditional": "實際", "pinyin": "shíjì", "english": "actual; real; practical" },
  { "chinese": "实习", "traditional": "實習", "pinyin": "shíxí", "english": "internship; practice" },
  { "chinese": "实现", "traditional": "實現", "pinyin": "shíxiàn", "english": "to realize; to achieve" },
  { "chinese": "实在", "traditional": "實在", "pinyin": "shízài", "english": "real; truly; indeed" },
  { "chinese": "实在", "traditional": "實在", "pinyin": "shízai", "english": "honest; reliable" },
  { "chinese": "食物", "traditional": "食物", "pinyin": "shíwù", "english": "food" },
  { "chinese": "使用", "traditional": "使用", "pinyin": "shǐyòng", "english": "to use; to employ" },
  { "chinese": "市", "traditional": "市", "pinyin": "shì", "english": "city; market" },
  { "chinese": "市长", "traditional": "市長", "pinyin": "shìzhǎng", "english": "mayor" },
  { "chinese": "事情", "traditional": "事情", "pinyin": "shìqing", "english": "thing; matter; affair" },
  { "chinese": "收", "traditional": "收", "pinyin": "shōu", "english": "to collect; to receive" },
  { "chinese": "收到", "traditional": "收到", "pinyin": "shōudào", "english": "to receive; to get" },
  { "chinese": "收入", "traditional": "收入", "pinyin": "shōurù", "english": "income; revenue" },
  { "chinese": "手表", "traditional": "手表", "pinyin": "shǒubiǎo", "english": "watch; wristwatch" },
  { "chinese": "受到", "traditional": "受到", "pinyin": "shòudào", "english": "to receive; to be subjected to" },
  { "chinese": "舒服", "traditional": "舒服", "pinyin": "shūfu", "english": "comfortable; pleasant" },
  { "chinese": "熟", "traditional": "熟", "pinyin": "shú", "english": "ripe; cooked; familiar" },
  { "chinese": "数", "traditional": "數", "pinyin": "shǔ", "english": "to count; to number" },
  { "chinese": "数字", "traditional": "數字", "pinyin": "shùzì", "english": "number; numeral; digit" },
  { "chinese": "水平", "traditional": "水平", "pinyin": "shuǐpíng", "english": "level; standard" },
  { "chinese": "顺利", "traditional": "順利", "pinyin": "shùnlì", "english": "smooth; successful" },
  { "chinese": "说明", "traditional": "說明", "pinyin": "shuōmíng", "english": "to explain; to illustrate" },
  { "chinese": "司机", "traditional": "司機", "pinyin": "sījī", "english": "driver" },
  { "chinese": "送到", "traditional": "送到", "pinyin": "sòngdào", "english": "to send to; to deliver to" },
  { "chinese": "送给", "traditional": "送給", "pinyin": "sònggěi", "english": "to give to; to present to" },
  { "chinese": "算", "traditional": "算", "pinyin": "suàn", "english": "to calculate; to count" },
  { "chinese": "虽然", "traditional": "雖然", "pinyin": "suīrán", "english": "although; though" },
  { "chinese": "随便", "traditional": "隨便", "pinyin": "suíbiàn", "english": "casual; random; as you like" },
  { "chinese": "随时", "traditional": "隨時", "pinyin": "suíshí", "english": "at any time; anytime" },
  { "chinese": "所以", "traditional": "所以", "pinyin": "suǒyǐ", "english": "so; therefore" },
  { "chinese": "所有", "traditional": "所有", "pinyin": "suǒyǒu", "english": "all; every" },
  { "chinese": "它", "traditional": "它", "pinyin": "tā", "english": "it" },
  { "chinese": "它们", "traditional": "它們", "pinyin": "tāmen", "english": "they; them (non-human)" },
  { "chinese": "太太", "traditional": "太太", "pinyin": "tàitai", "english": "wife; Mrs." },
  { "chinese": "太阳", "traditional": "太陽", "pinyin": "tàiyáng", "english": "sun" },
  { "chinese": "态度", "traditional": "態度", "pinyin": "tàidu", "english": "attitude; manner" },
  { "chinese": "讨论", "traditional": "討論", "pinyin": "tǎolùn", "english": "to discuss; discussion" },
  { "chinese": "套", "traditional": "套", "pinyin": "tào", "english": "set; suite; measure word" },
  { "chinese": "特别", "traditional": "特別", "pinyin": "tèbié", "english": "special; especially" },
  { "chinese": "特点", "traditional": "特點", "pinyin": "tèdiǎn", "english": "characteristic; feature" },
  { "chinese": "疼", "traditional": "疼", "pinyin": "téng", "english": "to hurt; to ache; pain" },
  { "chinese": "提", "traditional": "提", "pinyin": "tí", "english": "to carry; to lift; to mention" },
  { "chinese": "提出", "traditional": "提出", "pinyin": "tíchū", "english": "to put forward; to propose" },
  { "chinese": "提到", "traditional": "提到", "pinyin": "tídào", "english": "to mention; to refer to" },
  { "chinese": "提高", "traditional": "提高", "pinyin": "tígāo", "english": "to improve; to enhance" },
  { "chinese": "题", "traditional": "題", "pinyin": "tí", "english": "topic; question; problem" },
  { "chinese": "体育", "traditional": "體育", "pinyin": "tǐyù", "english": "sports; physical education" },
  { "chinese": "体育场", "traditional": "體育場", "pinyin": "tǐyùchǎng", "english": "stadium; sports field" },
  { "chinese": "体育馆", "traditional": "體育館", "pinyin": "tǐyùguǎn", "english": "gymnasium; sports hall" },
  { "chinese": "天上", "traditional": "天上", "pinyin": "tiānshàng", "english": "in the sky; heaven" },
  { "chinese": "条", "traditional": "條", "pinyin": "tiáo", "english": "strip; measure word" },
  { "chinese": "条件", "traditional": "條件", "pinyin": "tiáojiàn", "english": "condition; requirement" },
  { "chinese": "听讲", "traditional": "聽講", "pinyin": "tīngjiǎng", "english": "to attend a lecture" },
  { "chinese": "听说", "traditional": "聽說", "pinyin": "tīngshuō", "english": "to hear; it is said" },
  { "chinese": "停", "traditional": "停", "pinyin": "tíng", "english": "to stop; to halt" },
  { "chinese": "停车", "traditional": "停車", "pinyin": "tíngchē", "english": "to park" },
  { "chinese": "停车场", "traditional": "停車場", "pinyin": "tíngchēchǎng", "english": "parking lot" },
  { "chinese": "挺", "traditional": "挺", "pinyin": "tǐng", "english": "quite; very; rather" },
  { "chinese": "挺好", "traditional": "挺好", "pinyin": "tǐnghǎo", "english": "quite good; pretty good" },
  { "chinese": "通", "traditional": "通", "pinyin": "tōng", "english": "through; to understand" },
  { "chinese": "通过", "traditional": "通過", "pinyin": "tōngguò", "english": "to pass through; to adopt" },
  { "chinese": "通知", "traditional": "通知", "pinyin": "tōngzhī", "english": "to notify; notice" },
  { "chinese": "同时", "traditional": "同時", "pinyin": "tóngshí", "english": "at the same time; meanwhile" },
  { "chinese": "同事", "traditional": "同事", "pinyin": "tóngshì", "english": "colleague; coworker" },
  { "chinese": "同样", "traditional": "同樣", "pinyin": "tóngyàng", "english": "same; similar" },
  { "chinese": "头", "traditional": "頭", "pinyin": "tóu", "english": "head; beginning; measure word" },
  { "chinese": "头", "traditional": "頭", "pinyin": "tou", "english": "suffix (inside, outside)" },
  { "chinese": "头发", "traditional": "頭髮", "pinyin": "tóufa", "english": "hair" },
  { "chinese": "图片", "traditional": "圖片", "pinyin": "túpiàn", "english": "picture; image; photo" },
  { "chinese": "推", "traditional": "推", "pinyin": "tuī", "english": "to push; to promote" },
  { "chinese": "腿", "traditional": "腿", "pinyin": "tuǐ", "english": "leg" },
  { "chinese": "外地", "traditional": "外地", "pinyin": "wàidì", "english": "other places; out of town" },
  { "chinese": "外卖", "traditional": "外賣", "pinyin": "wàimài", "english": "takeout; delivery food" },
  { "chinese": "完", "traditional": "完", "pinyin": "wán", "english": "to finish; to complete" },
  { "chinese": "完成", "traditional": "完成", "pinyin": "wánchéng", "english": "to complete; to accomplish" },
  { "chinese": "完全", "traditional": "完全", "pinyin": "wánquán", "english": "completely; totally" },
  { "chinese": "晚安", "traditional": "晚安", "pinyin": "wǎn'ān", "english": "good night" },
  { "chinese": "晚报", "traditional": "晚報", "pinyin": "wǎnbào", "english": "evening newspaper" },
  { "chinese": "晚餐", "traditional": "晚餐", "pinyin": "wǎncān", "english": "dinner; supper" },
  { "chinese": "晚会", "traditional": "晚會", "pinyin": "wǎnhuì", "english": "evening party; gala" },
  { "chinese": "碗", "traditional": "碗", "pinyin": "wǎn", "english": "bowl" },
  { "chinese": "万", "traditional": "萬", "pinyin": "wàn", "english": "ten thousand" },
  { "chinese": "网", "traditional": "網", "pinyin": "wǎng", "english": "net; network; internet" },
  { "chinese": "网球", "traditional": "網球", "pinyin": "wǎngqiú", "english": "tennis" },
  { "chinese": "网站", "traditional": "網站", "pinyin": "wǎngzhàn", "english": "website" },
  { "chinese": "往", "traditional": "往", "pinyin": "wǎng", "english": "toward; to go to" },
  { "chinese": "为", "traditional": "為", "pinyin": "wèi", "english": "for; because of; by" },
  { "chinese": "为什么", "traditional": "為什麼", "pinyin": "wèishénme", "english": "why; for what reason" },
  { "chinese": "位", "traditional": "位", "pinyin": "wèi", "english": "position; measure word for people" },
  { "chinese": "味道", "traditional": "味道", "pinyin": "wèidào", "english": "taste; flavor" },
  { "chinese": "喂", "traditional": "喂", "pinyin": "wèi", "english": "hello; hey (interjection)" },
  { "chinese": "温度", "traditional": "溫度", "pinyin": "wēndù", "english": "temperature" },
  { "chinese": "闻", "traditional": "聞", "pinyin": "wén", "english": "to smell; to hear" },
  { "chinese": "问路", "traditional": "問路", "pinyin": "wènlù", "english": "to ask for directions" },
  { "chinese": "问题", "traditional": "問題", "pinyin": "wèntí", "english": "question; problem; issue" },
  { "chinese": "午餐", "traditional": "午餐", "pinyin": "wǔcān", "english": "lunch" },
  { "chinese": "午睡", "traditional": "午睡", "pinyin": "wǔshuì", "english": "afternoon nap; siesta" },
  { "chinese": "西北", "traditional": "西北", "pinyin": "xīběi", "english": "northwest" },
  { "chinese": "西餐", "traditional": "西餐", "pinyin": "xīcān", "english": "Western food" },
  { "chinese": "西方", "traditional": "西方", "pinyin": "xīfāng", "english": "west; the West" },
  { "chinese": "西南", "traditional": "西南", "pinyin": "xīnán", "english": "southwest" },
  { "chinese": "西医", "traditional": "西醫", "pinyin": "xīyī", "english": "Western medicine" },
  { "chinese": "习惯", "traditional": "習慣", "pinyin": "xíguàn", "english": "habit; to be used to" },
  { "chinese": "洗衣机", "traditional": "洗衣機", "pinyin": "xǐyījī", "english": "washing machine" },
  { "chinese": "洗澡", "traditional": "洗澡", "pinyin": "xǐzǎo", "english": "to take a bath/shower" },
  { "chinese": "下", "traditional": "下", "pinyin": "xià", "english": "time; round (measure word)" },
  { "chinese": "下雪", "traditional": "下雪", "pinyin": "xiàxuě", "english": "to snow; snowing" },
  { "chinese": "下周", "traditional": "下周", "pinyin": "xiàzhōu", "english": "next week" },
  { "chinese": "夏天", "traditional": "夏天", "pinyin": "xiàtiān", "english": "summer" },
  { "chinese": "相同", "traditional": "相同", "pinyin": "xiāngtóng", "english": "same; identical" },
  { "chinese": "相信", "traditional": "相信", "pinyin": "xiāngxìn", "english": "to believe; to trust" },
  { "chinese": "响", "traditional": "響", "pinyin": "xiǎng", "english": "loud; to make a sound" },
  { "chinese": "想到", "traditional": "想到", "pinyin": "xiǎngdào", "english": "to think of; to occur to" },
  { "chinese": "想法", "traditional": "想法", "pinyin": "xiǎngfǎ", "english": "idea; thought; opinion" },
  { "chinese": "想起", "traditional": "想起", "pinyin": "xiǎngqǐ", "english": "to remember; to recall" },
  { "chinese": "向", "traditional": "向", "pinyin": "xiàng", "english": "toward; to face" },
  { "chinese": "相机", "traditional": "相機", "pinyin": "xiàngjī", "english": "camera" },
  { "chinese": "像", "traditional": "像", "pinyin": "xiàng", "english": "to be like; to resemble" },
  { "chinese": "小", "traditional": "小", "pinyin": "xiǎo", "english": "young (prefix for names)" },
  { "chinese": "小声", "traditional": "小聲", "pinyin": "xiǎoshēng", "english": "in a low voice; quietly" },
  { "chinese": "小时候", "traditional": "小時候", "pinyin": "xiǎoshíhou", "english": "when young; childhood" },
  { "chinese": "小说", "traditional": "小說", "pinyin": "xiǎoshuō", "english": "novel; fiction" },
  { "chinese": "小心", "traditional": "小心", "pinyin": "xiǎoxīn", "english": "careful; be careful" },
  { "chinese": "小组", "traditional": "小組", "pinyin": "xiǎozǔ", "english": "small group; team" },
  { "chinese": "校园", "traditional": "校園", "pinyin": "xiàoyuán", "english": "campus; schoolyard" },
  { "chinese": "校长", "traditional": "校長", "pinyin": "xiàozhǎng", "english": "principal; headmaster" },
  { "chinese": "笑话", "traditional": "笑話", "pinyin": "xiàohua", "english": "joke" },
  { "chinese": "笑话儿", "traditional": "笑話兒", "pinyin": "xiàohuàr", "english": "joke" },
  { "chinese": "鞋", "traditional": "鞋", "pinyin": "xié", "english": "shoes" },
  { "chinese": "心里", "traditional": "心裡", "pinyin": "xīnlǐ", "english": "in one's heart; mentally" },
  { "chinese": "心情", "traditional": "心情", "pinyin": "xīnqíng", "english": "mood; feeling" },
  { "chinese": "心中", "traditional": "心中", "pinyin": "xīnzhōng", "english": "in one's heart; in mind" },
  { "chinese": "新闻", "traditional": "新聞", "pinyin": "xīnwén", "english": "news" },
  { "chinese": "信", "traditional": "信", "pinyin": "xìn", "english": "letter; to believe" },
  { "chinese": "信号", "traditional": "信號", "pinyin": "xìnhào", "english": "signal" },
  { "chinese": "信息", "traditional": "信息", "pinyin": "xìnxī", "english": "information; message" },
  { "chinese": "信心", "traditional": "信心", "pinyin": "xìnxīn", "english": "confidence; faith" },
  { "chinese": "信用卡", "traditional": "信用卡", "pinyin": "xìnyòngkǎ", "english": "credit card" },
  { "chinese": "星星", "traditional": "星星", "pinyin": "xīngxing", "english": "star" },
  { "chinese": "行动", "traditional": "行動", "pinyin": "xíngdòng", "english": "action; to take action" },
  { "chinese": "行人", "traditional": "行人", "pinyin": "xíngrén", "english": "pedestrian" },
  { "chinese": "行为", "traditional": "行為", "pinyin": "xíngwéi", "english": "behavior; conduct" },
  { "chinese": "姓", "traditional": "姓", "pinyin": "xìng", "english": "surname; family name" },
  { "chinese": "姓名", "traditional": "姓名", "pinyin": "xìngmíng", "english": "full name" },
  { "chinese": "休假", "traditional": "休假", "pinyin": "xiūjià", "english": "to take a vacation; holiday" },
  { "chinese": "许多", "traditional": "許多", "pinyin": "xǔduō", "english": "many; a lot of" },
  { "chinese": "选", "traditional": "選", "pinyin": "xuǎn", "english": "to choose; to select" },
  { "chinese": "学期", "traditional": "學期", "pinyin": "xuéqī", "english": "semester; term" },
  { "chinese": "雪", "traditional": "雪", "pinyin": "xuě", "english": "snow" },
  { "chinese": "颜色", "traditional": "顏色", "pinyin": "yánsè", "english": "color" },
  { "chinese": "眼", "traditional": "眼", "pinyin": "yǎn", "english": "eye" },
  { "chinese": "眼睛", "traditional": "眼睛", "pinyin": "yǎnjing", "english": "eyes" },
  { "chinese": "养", "traditional": "養", "pinyin": "yǎng", "english": "to raise; to keep; to support" },
  { "chinese": "样子", "traditional": "樣子", "pinyin": "yàngzi", "english": "appearance; look; style" },
  { "chinese": "要求", "traditional": "要求", "pinyin": "yāoqiú", "english": "to require; requirement" },
  { "chinese": "药", "traditional": "藥", "pinyin": "yào", "english": "medicine; drug" },
  { "chinese": "药店", "traditional": "藥店", "pinyin": "yàodiàn", "english": "pharmacy; drugstore" },
  { "chinese": "药片", "traditional": "藥片", "pinyin": "yàopiàn", "english": "pill; tablet" },
  { "chinese": "药水", "traditional": "藥水", "pinyin": "yàoshuǐ", "english": "liquid medicine; potion" },
  { "chinese": "也许", "traditional": "也許", "pinyin": "yěxǔ", "english": "perhaps; maybe" },
  { "chinese": "夜", "traditional": "夜", "pinyin": "yè", "english": "night" },
  { "chinese": "夜里", "traditional": "夜裡", "pinyin": "yèlǐ", "english": "at night; during the night" },
  { "chinese": "一部分", "traditional": "一部分", "pinyin": "yībùfen", "english": "a part; a portion" },
  { "chinese": "一定", "traditional": "一定", "pinyin": "yīdìng", "english": "certain; definitely; must" },
  { "chinese": "一共", "traditional": "一共", "pinyin": "yīgòng", "english": "altogether; in total" },
  { "chinese": "一会儿", "traditional": "一會兒", "pinyin": "yīhuìr", "english": "a moment; a while" },
  { "chinese": "一路平安", "traditional": "一路平安", "pinyin": "yīlùpíng'ān", "english": "have a safe trip" },
  { "chinese": "一路顺风", "traditional": "一路順風", "pinyin": "yīlùshùnfēng", "english": "bon voyage; have a good trip" },
  { "chinese": "已经", "traditional": "已經", "pinyin": "yǐjīng", "english": "already" },
  { "chinese": "以后", "traditional": "以後", "pinyin": "yǐhòu", "english": "after; later; in the future" },
  { "chinese": "以前", "traditional": "以前", "pinyin": "yǐqián", "english": "before; previously" },
  { "chinese": "以上", "traditional": "以上", "pinyin": "yǐshàng", "english": "above; over; more than" },
  { "chinese": "以外", "traditional": "以外", "pinyin": "yǐwài", "english": "beyond; outside; except" },
  { "chinese": "以为", "traditional": "以為", "pinyin": "yǐwéi", "english": "to think; to believe" },
  { "chinese": "以下", "traditional": "以下", "pinyin": "yǐxià", "english": "below; under; following" },
  { "chinese": "椅子", "traditional": "椅子", "pinyin": "yǐzi", "english": "chair" },
  { "chinese": "一般", "traditional": "一般", "pinyin": "yībān", "english": "general; ordinary; same" },
  { "chinese": "一点点", "traditional": "一點點", "pinyin": "yīdiǎndiǎn", "english": "a little bit" },
  { "chinese": "一生", "traditional": "一生", "pinyin": "yīshēng", "english": "lifetime; all one's life" },
  { "chinese": "一直", "traditional": "一直", "pinyin": "yīzhí", "english": "straight; continuously; all along" },
  { "chinese": "亿", "traditional": "億", "pinyin": "yì", "english": "hundred million" },
  { "chinese": "意见", "traditional": "意見", "pinyin": "yìjiàn", "english": "opinion; suggestion" },
  { "chinese": "意思", "traditional": "意思", "pinyin": "yìsi", "english": "meaning; intention" },
  { "chinese": "因为", "traditional": "因為", "pinyin": "yīnwèi", "english": "because; due to" },
  { "chinese": "阴", "traditional": "陰", "pinyin": "yīn", "english": "cloudy; overcast; yin" },
  { "chinese": "阴天", "traditional": "陰天", "pinyin": "yīntiān", "english": "cloudy day; overcast" },
  { "chinese": "音节", "traditional": "音節", "pinyin": "yīnjié", "english": "syllable" },
  { "chinese": "音乐", "traditional": "音樂", "pinyin": "yīnyuè", "english": "music" },
  { "chinese": "音乐会", "traditional": "音樂會", "pinyin": "yīnyuèhuì", "english": "concert" },
  { "chinese": "银行", "traditional": "銀行", "pinyin": "yínháng", "english": "bank" },
  { "chinese": "银行卡", "traditional": "銀行卡", "pinyin": "yínhángkǎ", "english": "bank card; debit card" },
  { "chinese": "应该", "traditional": "應該", "pinyin": "yīnggāi", "english": "should; ought to" },
  { "chinese": "英文", "traditional": "英文", "pinyin": "yīngwén", "english": "English (language)" },
  { "chinese": "英语", "traditional": "英語", "pinyin": "yīngyǔ", "english": "English (language)" },
  { "chinese": "影片", "traditional": "影片", "pinyin": "yǐngpiàn", "english": "film; movie" },
  { "chinese": "影响", "traditional": "影響", "pinyin": "yǐngxiǎng", "english": "influence; effect; to affect" },
  { "chinese": "永远", "traditional": "永遠", "pinyin": "yǒngyuǎn", "english": "forever; always" },
  { "chinese": "油", "traditional": "油", "pinyin": "yóu", "english": "oil; fat; grease" },
  { "chinese": "游客", "traditional": "遊客", "pinyin": "yóukè", "english": "tourist; visitor" },
  { "chinese": "友好", "traditional": "友好", "pinyin": "yǒuhǎo", "english": "friendly; amicable" },
  { "chinese": "有空儿", "traditional": "有空兒", "pinyin": "yǒukòngr", "english": "to be free; to have time" },
  { "chinese": "有人", "traditional": "有人", "pinyin": "yǒurén", "english": "someone; somebody" },
  { "chinese": "有点儿", "traditional": "有點兒", "pinyin": "yǒudiǎnr", "english": "a little; somewhat" },
  { "chinese": "有意思", "traditional": "有意思", "pinyin": "yǒuyìsi", "english": "interesting; meaningful" },
  { "chinese": "又", "traditional": "又", "pinyin": "yòu", "english": "again; also; both... and" },
  { "chinese": "鱼", "traditional": "魚", "pinyin": "yú", "english": "fish" },
  { "chinese": "语言", "traditional": "語言", "pinyin": "yǔyán", "english": "language" },
  { "chinese": "原来", "traditional": "原來", "pinyin": "yuánlái", "english": "original; originally; it turns out" },
  { "chinese": "原因", "traditional": "原因", "pinyin": "yuányīn", "english": "reason; cause" },
  { "chinese": "院", "traditional": "院", "pinyin": "yuàn", "english": "courtyard; institution; college" },
  { "chinese": "院长", "traditional": "院長", "pinyin": "yuànzhǎng", "english": "dean; president (of college)" },
  { "chinese": "院子", "traditional": "院子", "pinyin": "yuànzi", "english": "courtyard; yard" },
  { "chinese": "愿意", "traditional": "願意", "pinyin": "yuànyì", "english": "willing; to be willing" },
  { "chinese": "月份", "traditional": "月份", "pinyin": "yuèfèn", "english": "month" },
  { "chinese": "月亮", "traditional": "月亮", "pinyin": "yuèliang", "english": "moon" },
  { "chinese": "越", "traditional": "越", "pinyin": "yuè", "english": "the more... the more" },
  { "chinese": "越来越", "traditional": "越來越", "pinyin": "yuèláiyuè", "english": "more and more" },
  { "chinese": "云", "traditional": "雲", "pinyin": "yún", "english": "cloud" },
  { "chinese": "运动", "traditional": "運動", "pinyin": "yùndòng", "english": "sports; exercise; movement" },
  { "chinese": "咱", "traditional": "咱", "pinyin": "zán", "english": "we; us (inclusive)" },
  { "chinese": "咱们", "traditional": "咱們", "pinyin": "zánmen", "english": "we; us (inclusive)" },
  { "chinese": "脏", "traditional": "髒", "pinyin": "zāng", "english": "dirty; filthy" },
  { "chinese": "早餐", "traditional": "早餐", "pinyin": "zǎocān", "english": "breakfast" },
  { "chinese": "早晨", "traditional": "早晨", "pinyin": "zǎochén", "english": "early morning" },
  { "chinese": "早就", "traditional": "早就", "pinyin": "zǎojiù", "english": "long ago; for a long time" },
  { "chinese": "怎么办", "traditional": "怎麼辦", "pinyin": "zěnmebàn", "english": "what to do; how to handle" },
  { "chinese": "怎么样", "traditional": "怎麼樣", "pinyin": "zěnmeyàng", "english": "how; how about" },
  { "chinese": "怎样", "traditional": "怎樣", "pinyin": "zěnyàng", "english": "how; in what way" },
  { "chinese": "占", "traditional": "佔", "pinyin": "zhàn", "english": "to occupy; to take up" },
  { "chinese": "站", "traditional": "站", "pinyin": "zhàn", "english": "to stand; station" },
  { "chinese": "站住", "traditional": "站住", "pinyin": "zhànzhù", "english": "to stop; to halt" },
  { "chinese": "长", "traditional": "長", "pinyin": "zhǎng", "english": "to grow; to develop" },
  { "chinese": "长大", "traditional": "長大", "pinyin": "zhǎngdà", "english": "to grow up" },
  { "chinese": "找出", "traditional": "找出", "pinyin": "zhǎochū", "english": "to find out; to discover" },
  { "chinese": "照顾", "traditional": "照顧", "pinyin": "zhàogù", "english": "to take care of; to look after" },
  { "chinese": "照片", "traditional": "照片", "pinyin": "zhàopiàn", "english": "photograph; photo" },
  { "chinese": "照相", "traditional": "照相", "pinyin": "zhàoxiàng", "english": "to take a photo" },
  { "chinese": "这么", "traditional": "這麼", "pinyin": "zhème", "english": "so; like this; this way" },
  { "chinese": "这时候", "traditional": "這時候", "pinyin": "zhèshíhou", "english": "at this time; now" },
  { "chinese": "这样", "traditional": "這樣", "pinyin": "zhèyàng", "english": "this way; like this; such" },
  { "chinese": "真正", "traditional": "真正", "pinyin": "zhēnzhèng", "english": "real; true; genuine" },
  { "chinese": "正常", "traditional": "正常", "pinyin": "zhèngcháng", "english": "normal; regular" },
  { "chinese": "正好", "traditional": "正好", "pinyin": "zhènghǎo", "english": "just right; exactly" },
  { "chinese": "正确", "traditional": "正確", "pinyin": "zhèngquè", "english": "correct; right; proper" },
  { "chinese": "正是", "traditional": "正是", "pinyin": "zhèngshì", "english": "exactly; precisely" },
  { "chinese": "直接", "traditional": "直接", "pinyin": "zhíjiē", "english": "direct; directly" },
  { "chinese": "只", "traditional": "只", "pinyin": "zhǐ", "english": "only; just; merely" },
  { "chinese": "只能", "traditional": "只能", "pinyin": "zhǐnéng", "english": "can only; have to" },
  { "chinese": "只要", "traditional": "只要", "pinyin": "zhǐyào", "english": "as long as; only if" },
  { "chinese": "纸", "traditional": "紙", "pinyin": "zhǐ", "english": "paper" },
  { "chinese": "中餐", "traditional": "中餐", "pinyin": "zhōngcān", "english": "Chinese food; lunch" },
  { "chinese": "中级", "traditional": "中級", "pinyin": "zhōngjí", "english": "intermediate; middle level" },
  { "chinese": "中年", "traditional": "中年", "pinyin": "zhōngnián", "english": "middle age; middle-aged" },
  { "chinese": "中小学", "traditional": "中小學", "pinyin": "zhōngxiǎoxué", "english": "primary and secondary schools" },
  { "chinese": "中心", "traditional": "中心", "pinyin": "zhōngxīn", "english": "center; heart; core" },
  { "chinese": "中医", "traditional": "中醫", "pinyin": "zhōngyī", "english": "traditional Chinese medicine" },
  { "chinese": "重点", "traditional": "重點", "pinyin": "zhòngdiǎn", "english": "key point; emphasis" },
  { "chinese": "重视", "traditional": "重視", "pinyin": "zhòngshì", "english": "to attach importance to" },
  { "chinese": "周", "traditional": "周", "pinyin": "zhōu", "english": "week; cycle" },
  { "chinese": "周末", "traditional": "周末", "pinyin": "zhōumò", "english": "weekend" },
  { "chinese": "周年", "traditional": "周年", "pinyin": "zhōunián", "english": "anniversary" },
  { "chinese": "主人", "traditional": "主人", "pinyin": "zhǔrén", "english": "host; master; owner" },
  { "chinese": "主要", "traditional": "主要", "pinyin": "zhǔyào", "english": "main; principal; major" },
  { "chinese": "住房", "traditional": "住房", "pinyin": "zhùfáng", "english": "housing; residence" },
  { "chinese": "住院", "traditional": "住院", "pinyin": "zhùyuàn", "english": "to be hospitalized" },
  { "chinese": "装", "traditional": "裝", "pinyin": "zhuāng", "english": "to install; to pretend; to pack" },
  { "chinese": "准确", "traditional": "準確", "pinyin": "zhǔnquè", "english": "accurate; precise" },
  { "chinese": "自己", "traditional": "自己", "pinyin": "zìjǐ", "english": "oneself; self" },
  { "chinese": "自行车", "traditional": "自行車", "pinyin": "zìxíngchē", "english": "bicycle; bike" },
  { "chinese": "自由", "traditional": "自由", "pinyin": "zìyóu", "english": "free; freedom; liberty" },
  { "chinese": "字典", "traditional": "字典", "pinyin": "zìdiǎn", "english": "dictionary" },
  { "chinese": "走过", "traditional": "走過", "pinyin": "zǒuguò", "english": "to walk past; to go through" },
  { "chinese": "走进", "traditional": "走進", "pinyin": "zǒujìn", "english": "to walk into; to enter" },
  { "chinese": "走开", "traditional": "走開", "pinyin": "zǒukāi", "english": "to go away; to leave" },
  { "chinese": "租", "traditional": "租", "pinyin": "zū", "english": "to rent; to lease" },
  { "chinese": "组", "traditional": "組", "pinyin": "zǔ", "english": "group; team; to organize" },
  { "chinese": "组成", "traditional": "組成", "pinyin": "zǔchéng", "english": "to compose; to form" },
  { "chinese": "组长", "traditional": "組長", "pinyin": "zǔzhǎng", "english": "group leader; team leader" },
  { "chinese": "嘴", "traditional": "嘴", "pinyin": "zuǐ", "english": "mouth" },
  { "chinese": "最近", "traditional": "最近", "pinyin": "zuìjìn", "english": "recently; lately; nearest" },
  { "chinese": "作家", "traditional": "作家", "pinyin": "zuòjiā", "english": "writer; author" },
  { "chinese": "作文", "traditional": "作文", "pinyin": "zuòwén", "english": "composition; essay" },
  { "chinese": "作业", "traditional": "作業", "pinyin": "zuòyè", "english": "homework; assignment" },
  { "chinese": "作用", "traditional": "作用", "pinyin": "zuòyòng", "english": "effect; function; role" },
  { "chinese": "座", "traditional": "座", "pinyin": "zuò", "english": "seat; measure word for buildings" },
  { "chinese": "座位", "traditional": "座位", "pinyin": "zuòwèi", "english": "seat" },
  { "chinese": "做到", "traditional": "做到", "pinyin": "zuòdào", "english": "to achieve; to accomplish" },
  { "chinese": "做法", "traditional": "做法", "pinyin": "zuòfǎ", "english": "way of doing; method; practice" },
  { "chinese": "做饭", "traditional": "做飯", "pinyin": "zuòfàn", "english": "to cook; to prepare a meal" }
];
